### ISSUE TITLE
我遇到的问题是bug吗

### ISSUE THREAD

**Issue by jipeng0918** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#10]
![image](https://user-images.githubusercontent.com/43375185/163673058-7bb7892c-d3c1-46b6-b117-a3f65177ee0c.png)
批注后正常

![image](https://user-images.githubusercontent.com/43375185/163673089-aaa3b297-b7af-467e-87c8-8c29cea44092.png)
软件重启后，批注没了。。。。。

**Comment by Zuoqiu-Yingyi** [comment]
我这里没有遇到过😂

**Comment by Zuoqiu-Yingyi** [comment]
[fix: 修复批注功能块属性无法写入问题](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/commit/5a85c8831a3e4375ee4b551754d590cd746f8fd6)
在这里应该修复了, 请继续关注
