### ISSUE TITLE
dark+主题打开自适应宽度的bug

### ISSUE THREAD

**Issue by Chenm4** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#101]
打开自适应宽度后无法对H标题进行块引用（右键没有弹出相应的菜单），其他的都能进行块引用，关闭自适应宽度则可以进行块引用，另外建议是否能人为更改宽度，感觉每个人需要的宽度不一样，默认主题的宽度有点大而dark+的宽度有点小

**Comment by Zuoqiu-Yingyi** [comment]
> 打开自适应宽度后无法对H标题进行块引用（右键没有弹出相应的菜单），其他的都能进行块引用，关闭自适应宽度则可以进行块引用，另外建议是否能人为更改宽度，感觉每个人需要的宽度不一样，默认主题的宽度有点大而dark+的宽度有点小

1. 光标在其他块中时右键单击块才能出现块菜单
2. 启用自适应宽度时文档具体的边距可以通过设置 CSS 变量 `--custom-editor-padding-left` 与 `--custom-editor-padding-right` 分别自定义

**Comment by Chenm4** [comment]
感谢感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月6日(星期二) 上午10:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Zuoqiu-Yingyi/siyuan-theme-dark-plus] dark+主题打开自适应宽度的bug (Issue #101)





  
打开自适应宽度后无法对H标题进行块引用（右键没有弹出相应的菜单），其他的都能进行块引用，关闭自适应宽度则可以进行块引用，另外建议是否能人为更改宽度，感觉每个人需要的宽度不一样，默认主题的宽度有点大而dark+的宽度有点小
   
光标在其他块中时右键单击块才能出现块菜单
 
启用自适应宽度时文档具体的边距可以通过设置 CSS 变量 --custom-editor-padding-left 与 --custom-editor-padding-right 分别自定义
