### ISSUE TITLE
暗色模式下 mermaid 通过设置%%{}%% 无效

### ISSUE THREAD

**Issue by jhzerone** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#104]
`
%%{init: {'theme': 'forest'}}%%
gantt
dateFormat  YYYY-MM-DD
title Adding GANTT diagram to mermaid
excludes weekdays 2014-01-10

section A section
Completed task            :done,    des1, 2014-01-06,2014-01-08
Active task               :active,  des2, 2014-01-09, 3d
Future task               :         des3, after des2, 5d
Future task2               :         des4, after des3, 5d
`
![image](https://user-images.githubusercontent.com/58368113/190888633-6b455041-08d7-4f24-aa1c-97ac632d9bee.png)
![image](https://user-images.githubusercontent.com/58368113/190888644-45226a80-9bf8-4953-bc77-24ebbcc2903e.png)
暗色模式下修改主题没有效果.

**Comment by Zuoqiu-Yingyi** [comment]
试试默认主题, 应该是思源在暗色主题下强行使用了 mermaid 的某款暗色主题

**Comment by jhzerone** [comment]
默认主题也是不行的
