### ISSUE TITLE
右键菜单-显示标记文本失效

### ISSUE THREAD

**Issue by mdzz2048** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#107]
虽然成功设置了块属性，但是刷新后还是无法显示内容
![image](https://user-images.githubusercontent.com/86549958/192218830-ed55ead4-653c-4e33-a7f0-a8accde4654e.png)

是不是因为 span-mark.css 文件里缺少了 mark-display 部分的代码？ https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/blob/f67f23d69485651120b9b3579cadf008bd2caadb/style/dynamic-module/mark-display.css#L2-L9)

**Comment by Zuoqiu-Yingyi** [comment]
已于 [3f9dde2](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/commit/3f9dde2e6741729b5a9aa86ecf353eb927d8e21c) 修复
