### ISSUE TITLE
点击长文档树的文档后，自动跳到最顶端

### ISSUE THREAD

**Issue by zihuzi** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#108]
如题，当文档树里文档很多时，下拉滑动条，点击打开文档后，文档树自动跳到最顶端。
ps: 其他主题不会这样。
ps: SiYuan最新版v2.2.2，主题也是最新版。

**Comment by Zuoqiu-Yingyi** [comment]
> 如题，当文档树里文档很多时，下拉滑动条，点击打开文档后，文档树自动跳到最顶端。 ps: 其他主题不会这样。 ps: SiYuan最新版v2.2.2，主题也是最新版。

这是因为文档树的列表辅助线导致的, 文档树的列表辅助线已于 [5adfbf9](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/commit/5adfbf9a8ff4585f3a96797f6bdad9af93ec795b) 移除, 主题下个版本应该能修复
