### ISSUE TITLE
文档树 Bug

### ISSUE THREAD

**Issue by abc1206** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#110]
在侧栏文档树打开或收起多级文档时，自动回到文档树顶部。
思源默认主题下无该问题。
思源笔记版本：v2.2.3，Dark+ 版本：v1.3.1
[ [主题 Dark+] 文档树 Bug](https://ld246.com/article/1664436647294)

**Comment by Zuoqiu-Yingyi** [comment]
Duplicate #108
