### ISSUE TITLE
请问如何自定义字体颜色池

### ISSUE THREAD

**Issue by tko81** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#111]
没要要盯着电脑十几个小时，默认字体颜色有点太亮了，能否自定义颜色，之前在右下角里的开发者工具改过，但是重启后就失去效果了，请问自定义字体属性在哪个本地文件修改呢？
<img width="123" alt="image" src="https://user-images.githubusercontent.com/104875084/193435507-8df03bb5-f75f-4836-9c8b-40104a73340c.png">

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/104875084/193435491-ac2bb1fd-f144-4bfc-96e2-b7a69cb3d9ad.png">

**Comment by tko81** [comment]
<img width="797" alt="image" src="https://user-images.githubusercontent.com/104875084/193435597-9e098d82-4604-4cdd-b631-26e2541a43dd.png">
已经找到本地文件，但为什么在本地css内修改了颜色之后，重启思源，还是会回到之前的颜色代码呢，思源每次重启会自动重置本地配置文件吗

**Comment by tko81** [comment]
修改完数据之后我把权限改为只读，思源直接打不开了，求大佬支招（修改个颜色好难）
<img width="265" alt="image" src="https://user-images.githubusercontent.com/104875084/193435674-911f2e60-8f70-453e-ad89-8b285e616d4b.png">

**Comment by Zuoqiu-Yingyi** [comment]
> <img alt="image" width="797" src="https://user-images.githubusercontent.com/104875084/193435597-9e098d82-4604-4cdd-b631-26e2541a43dd.png">
> 
> 已经找到本地文件，但为什么在本地css内修改了颜色之后，重启思源，还是会回到之前的颜色代码呢，思源每次重启会自动重置本地配置文件吗

默认配色文件缺失会在思源启动时重置, 想要自定义配色的话可以新建 `data/widgets/custom-light.css` 与  `data/widgets/custom-light.css` 两个文件, 在里面设置需要覆盖的颜色配置

**Comment by tko81** [comment]
非常感谢！
________________________________
发件人: 颖逸 ***@***.***>
发送时间: 2022年10月2日 12:11
收件人: Zuoqiu-Yingyi/siyuan-theme-dark-plus ***@***.***>
抄送: tko81 ***@***.***>; Author ***@***.***>
主题: Re: [Zuoqiu-Yingyi/siyuan-theme-dark-plus] 请问如何自定义字体颜色池 (Issue #111)


[image]<https://user-images.githubusercontent.com/104875084/193435597-9e098d82-4604-4cdd-b631-26e2541a43dd.png>

已经找到本地文件，但为什么在本地css内修改了颜色之后，重启思源，还是会回到之前的颜色代码呢，思源每次重启会自动重置本地配置文件吗

默认配色文件缺失会在思源启动时重置, 想要自定义配色的话可以新建 data/widgets/custom-light.css 与 data/widgets/custom-light.css 两个文件, 在里面设置需要覆盖的颜色配置

―
