### ISSUE TITLE
列表可以支持转换成看板吗？

### ISSUE THREAD

**Issue by yuyuyu-github** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#113]
像salt这样
![image](https://user-images.githubusercontent.com/37429029/194890805-109929cc-7c26-43c2-87b1-e81cf7adcfb2.png)

![image](https://user-images.githubusercontent.com/37429029/194890733-9a073b54-0410-4db8-9ddb-a7782bc2bacc.png)

**Comment by yuyuyu-github** [comment]
好的(✿◕‿◕✿)

**Comment by yuyuyu-github** [comment]
对了，我用了其他主题的看板模式，发现一个很头疼的问题，就是拖动条放在了底部，导致左右拖动非常不方便。
希望看板模式的横向拖动条可以出现在顶部
[列表转看板以后，看板的左右拖动条能否放在顶部 · Issue #7 · royc01/salt](https://github.com/royc01/salt/issues/7)

**Comment by Zuoqiu-Yingyi** [comment]
> 对了，我用了其他主题的看板模式，发现一个很头疼的问题，就是看板拖动条放在了底部，导致左右拖动非常不方便。 希望看板模式的横向拖动条可以出现在顶部

可以试试 <kbd>Shift</kbd> + 鼠标滚轮 进行左右滚动
