### ISSUE TITLE
列表转表格，出现了文字叠在一起的情况

### ISSUE THREAD

**Issue by yuyuyu-github** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#114]
如图
![image](https://user-images.githubusercontent.com/37429029/194891352-5e82f31f-e970-4295-a29e-001091288f68.png)
转成表格，就出现堆叠的情况了
![image](https://user-images.githubusercontent.com/37429029/194891229-028d29a1-e2c3-468d-8ca1-066a6c61198a.png)

**Comment by Zuoqiu-Yingyi** [comment]
将每个列表项的第二行更改为软换行吧, 因为列表项是个容器块, 为了兼容下一级的列表块, 不太好处理~

**Comment by yuyuyu-github** [comment]
我都更换成软换行了，但是转成表格以后，还是这样ε(┬┬﹏┬┬)3
![image](https://user-images.githubusercontent.com/37429029/195040514-9d51bee0-de0b-406a-80a2-fc44daa038ff.png)
![image](https://user-images.githubusercontent.com/37429029/195040609-cf1ffc74-d705-420e-962a-812a36b0d7b0.png)

**Comment by yuyuyu-github** [comment]
* 主线任务进度跟踪

  1. 你当前的主线任务是什么？对你的价值是什么，值得继续吗？

      1. 找到一份开发工作
      2. 价值就是钱，养活自己
  2. 今天的主线任务推进了什么？符合预期吗？需要进行什么调整？

      1. 今天没有推进任何主线任务。主线任务还没有进入序列
  3. 当前主线任务总体进行到哪里了？能够按时进行交付呢？

      1. 还在刷面试题，还有200多道，只进行了1/3
* 请复盘你今天的时间投入以及对应的收获，他们匹配吗？

  * [X] 学习仁冲/潇潇/如何进入心流讲座

    * 投入***1h29***
    * ((20221009095748-pgox00a '番茄钟 正计时'))<br />((20221009173101-z9sqjia '大脑工作记忆容量'))
  * [X] 尝试用双链整理想法

    * 投入***45min***
    * 成功地整理了自己当天地笔记
  * [X] 制作一个复盘模板

    * 投入***1h33***
    * 成功制作了一份复盘模板的雏形。以问题的形式进行复盘。
* 你把今天的主要精力投入到了什么事情上？

  1. 工作
  2. 自我实现  √
  3. 琐事
* 自己早中晚的精神状态评价 (这个模块存疑）

  1. 早晨：状态良好，就是一直没有喝水。
  2. 下午：
  3. 晚上：
* 自己今日的作息是否正常？

  * [X] 7：00早起
    今天早上因为手机没电，导致闹钟没响，我每天应该检查，让手机电量充足，声音响铃

  * [X] 1：30午休<br />午休前在玩羊了个羊，这时间本来可以看赛博朋客边缘行者的，别tm再玩羊了个羊了，SB行为！！！

  * [X] 11：00睡眠
* 今天的饮食怎么样？

  * [X] 早餐
    吃的方便面，连着吃了一个星期方便面了，还有三包，哭了。。。
  * [X] 中餐

  * [X] 晚餐
    晚饭吃多了有点，菜都是我喜欢的菜。 我那个盘子如果强行堆菜就失效了
  * [X] 零食

    自己老是吃老妈买回来的花生，这玩意吃了长胖啊
* 今天是否有习惯没有完成？

  1. 打卡情况：【每天三杯水】的习惯，早上没能完成
  2. 波动原因：1. 杯子没洗，没水喝。2. 保温杯的水太难冷下来了，所以没法大口喝。
* 今天有什么引起你情绪波动的人和事吗？

  1. ((20221009221612-48q5are '难受'))
  2. ((20221009082343-ha38gza '内耗自己早上又开始因为女权在脑袋里面打架了。 这是极其影响心情，损耗状态的行为。 原因就是我在b站对一个女拳留言， 然后第二天，觉得有人会回复喷我，因此在脑袋里做预演。这种毫无意义，损自己的事...'))
  3. ((20221009090237-asq6hb5 '失望'))
  4. ((20221009151858-o7awso6 '警醒'))
  5. ((20221009220839-xqzmjx2 '放松'))
  6. ((20221009220936-neqwt61 '羡慕'))
  7. ((20221009220829-ejxzwb4 '惊喜'))
* 今天有什么值得记录的事件吗？

  1. ((20221009152416-ocwrd5g '买菜'))
* 今天的摸鱼放松的体验怎么样？

  1. 30分钟Apex，顺利完成任务，美滋滋
  2. ((20221009221728-ssb9wqh '赛博朋客边缘行者'))
* 今天自己在人际关系上面有什么拓展or问题吗？（家庭、朋友、同事、其他）

  1. 我今天在老爸吃饭的情况下，主动出门说话了，并且得到的是正面的反馈。
* 统计分析（请根据以上内容找到今天的关键问题，并落实解决）

  * [ ] 关键问题1：原来的杯子没找到，导致的口渴。
  * [ ] 关键问题2：别tm玩羊了个羊了！！！！
  * [X] 关键问题3：老妈买回来的花生，我总是吃

    花生吃完了
  * [ ] 关键问题4：保持手机晚上电量充足、开启闹铃模式。

    设置手机充电提醒
