### ISSUE TITLE
关于页签宽度的建议

### ISSUE THREAD

**Issue by Hyd19** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#115]
思源默认的页签关闭键有效范围比实际显示的阴影范围大，我在链滴中反馈这一问题，被告知“范围扩大是设计用意”：https://ld246.com/article/1665454158493 。这在默认主题下影响不会太大，因为页签宽度统一，设置得比较宽。而在 dark+ 中，页签宽度随文档名而变化，这时极易发生误触——想点击在中间范围切换页面，并未进入关闭键范围，也会关闭页签：
![image](https://user-images.githubusercontent.com/84370053/194985203-a04372e3-12c5-4a58-ac8e-2a6e2b71e672.png)
![image](https://user-images.githubusercontent.com/84370053/194985216-b5550af2-0d63-4434-b947-d5e62b40f2d3.png)

希望能限定页签宽度的最小值，以避免误触关闭页签，谢谢！

**Comment by Zuoqiu-Yingyi** [comment]
下个版本可以使用 CSS 变量 `--custom-tab-bar-item-min-width` 自定义最小宽度, 默认无最小宽度

**Comment by Hyd19** [comment]
> 下个版本可以使用 CSS 变量 `--custom-tab-bar-item-min-width` 自定义最小宽度, 默认无最小宽度

请教下，复制进custom.css后该怎么填啊？

:root {
  --custom-tab-bar-flex-wrap: nowrap; /* 单行显示 */

  /* 非钉住页签项最小宽度 */
  --custom-tab-bar-item-min-width: none;
}

**Comment by Zuoqiu-Yingyi** [comment]
> > 下个版本可以使用 CSS 变量 `--custom-tab-bar-item-min-width` 自定义最小宽度, 默认无最小宽度
> 
> 请教下，复制进custom.css后该怎么填啊？我把下面“none”替换为任何数字加上px或rem，都没有用，是格式不对吗？
> 
> :root { --custom-tab-bar-flex-wrap: nowrap; /* 单行显示 */
> 
> /* 非钉住页签项最小宽度 */ --custom-tab-bar-item-min-width: none; }

可能有缓存, 使用 Ctrl + F5 强制刷新一下页面试试
