### ISSUE TITLE
 模板预览界面或许可以扩宽

### ISSUE THREAD

**Issue by yuyuyu-github** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#119]
在使用模板的时候，经常发现因为模板的预览界面不够宽，导致模板在预览界面无法正常展示。（预览功能大多数情况变成摆设）
![image](https://user-images.githubusercontent.com/37429029/195284929-294224b3-ff25-42be-af08-4dbaaf8d7f01.png)

现在模板预览弹窗会占据1/4的屏幕，但右边所空出来的一半位置，我感觉其实也是无用的空间。

因为右半边屏幕一般情况下是空白。即使有内容，在左半边屏幕被挡住的情况下，右半边的信息也无法表达出原有的意思。

所以，或许，在/引用模板的时候，可以直接占据上/下方一半的屏幕。将右边这一半的空间也利用起来。(。・ω・。)
![QQ截图20221012155805](https://user-images.githubusercontent.com/37429029/195284596-6c22b0df-753c-4dd5-8054-8ee2e3060190.png)

**Comment by Zuoqiu-Yingyi** [comment]
下个版本支持 CSS 变量 `--custom-template-preview-width` 与 `--custom-template-preview-min-width` 设置模板预览窗口的宽度
