### ISSUE TITLE
列表辅助线接缝可能没焊好

### ISSUE THREAD

**Issue by 1995hanjian** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#12]
![image](https://user-images.githubusercontent.com/39188734/163832153-2f092b24-bc69-4a99-a5b6-25115d97bdb0.png)

大佬YYDS！（我前端小白，自己不会修，只能抱大腿了呜呜呜）

**Comment by 1995hanjian** [comment]
* 列表项块出现多个段落时，第一个、第二个段落的地方辅助线有缝隙
* 列表项块子段落引入嵌入块，辅助线会错开

**Comment by Zuoqiu-Yingyi** [comment]
> * 列表项块出现多个段落时，第一个、第二个段落的地方辅助线有缝隙
> * 列表项块子段落引入嵌入块，辅助线会错开

了解了, 之前刚焊了一个, 结果引入了这两个😂

**Comment by Zuoqiu-Yingyi** [comment]
@1995hanjian [fix: 修复列表辅助线错位问题 · Zuoqiu-Yingyi/siyuan-theme-dark-plus@4392e27](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/commit/4392e278428d5e6e67377485e2f34a8df5aa9e94)
