### ISSUE TITLE
请教一下，如何隐藏右半边这层多余的灰色背景？

### ISSUE THREAD

**Issue by yuyuyu-github** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#120]
如图
![QQ截图20221012082048](https://user-images.githubusercontent.com/37429029/195286575-760c9839-8867-4ac6-839b-debacaeb8be2.png)

MarkDown源码
# 面试题模板

> * **掌握程度**：
>
> * [ ] 已经掌握
>
> * [ ] 大致了解
>
> * [ ] 模糊/未掌握
>
> * **面试频率**：
>
> * [ ] 少见
>
> * [ ] 正常
>
> * [ ] 频繁
>
> * **难度**：
>
> * [ ] 简单
>
> * [ ] 适中
>
> * [ ] 困难
>
> * **策略**：
>
> * [ ] 了解即可
>
> * [ ] 掌握要点
>
> * [ ] 详细学习
>
> * **涉及知识点**：
> * **学习结果评估**：
>
> * **参考**：

* ​**答案：**

  * ‍
* **延申：**

  * [ ] ‍

‍

‍

**Comment by Zuoqiu-Yingyi** [comment]
你的 markdown 源码无法复现~
塞到代码块围栏里面试试
````markdown
```markdown
markdown 源码
```
````

**Comment by yuyuyu-github** [comment]
```markdown
# 面试题模板

> * **掌握程度**：
>
> * [ ] 已经掌握
>
> * [ ] 大致了解
>
> * [ ] 模糊/未掌握
>
> * **面试频率**：
>
> * [ ] 少见
>
> * [ ] 正常
>
> * [ ] 频繁
>
> * **难度**：
>
> * [ ] 简单
>
> * [ ] 适中
>
> * [ ] 困难
>
> * **策略**：
>
> * [ ] 了解即可
>
> * [ ] 掌握要点
>
> * [ ] 详细学习
>
> * **涉及知识点**：
> * **学习结果评估**：
>
> * **参考**：

* ​**答案：**

  * ‍
* **延申：**

  * [ ] ‍

‍

‍

markdown 源码
```

**Comment by yuyuyu-github** [comment]
> ```gfm
> # 面试题模板
> 
> > * **掌握程度**：
> >
> > * [ ] 已经掌握
> >
> > * [ ] 大致了解
> >
> > * [ ] 模糊/未掌握
> >
> > * **面试频率**：
> >
> > * [ ] 少见
> >
> > * [ ] 正常
> >
> > * [ ] 频繁
> >
> > * **难度**：
> >
> > * [ ] 简单
> >
> > * [ ] 适中
> >
> > * [ ] 困难
> >
> > * **策略**：
> >
> > * [ ] 了解即可
> >
> > * [ ] 掌握要点
> >
> > * [ ] 详细学习
> >
> > * **涉及知识点**：
> > * **学习结果评估**：
> >
> > * **参考**：
> 
> * ​**答案：**
> 
>   * ‍
> * **延申：**
> 
>   * [ ] ‍
> 
> ‍
> 
> ‍
> 
> markdown 源码
> ```

好吧，超级块是不是没法用markdown代码复现

**Comment by Zuoqiu-Yingyi** [comment]
> 好吧，超级块是不是没法用markdown代码复现＞︿＜

导出为模板试试, 或者直接 Ctrl+C 复制

**Comment by yuyuyu-github** [comment]
[面试题模板.md](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/files/9764515/default.md)

**Comment by Zuoqiu-Yingyi** [comment]
> [面试题模板.md](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/files/9764515/default.md)

我用默认主题发现也有这个问题, 在思源那里反馈一下吧(\*^▽^\*)

**Comment by yuyuyu-github** [comment]
问了，我选择就zhe'yang'b这样吧，反正是小问题╮（╯＿╰）╭
![image](https://user-images.githubusercontent.com/37429029/195350745-294573a8-143a-4306-8628-3607bf6d2bd7.png)
