### ISSUE TITLE
明亮与暗黑模式切换失效

### ISSUE THREAD

**Issue by everleap** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#121]
在明亮模式中，dark+依旧显示为暗黑模式的配置，重装主题之后依然无法解决。
![image](https://user-images.githubusercontent.com/96156946/195960896-0d81a483-e1a7-4425-a953-77c5e64cbb5c.png)

**Comment by Zuoqiu-Yingyi** [comment]
<kbd>Ctrl + F5</kbd> 重新加载一下试试, 可能加载时出现了错误

**Comment by everleap** [comment]
好的，谢谢，目前问题已解决
