### ISSUE TITLE
为什么我更新之后图标变得超级大了（如图所示）

### ISSUE THREAD

**Issue by git-zxx** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#122]
<img width="1080" alt="图标异常" src="https://user-images.githubusercontent.com/42286494/196120650-1931b20d-9a50-46a1-a048-08359868ee39.png">

**Comment by Zuoqiu-Yingyi** [comment]
旧有样式文件还保存在浏览器缓存中, 导致新旧样式同时生效, 需要禁用缓存刷新一次

**Comment by yuyuyu-github** [comment]
![image](https://user-images.githubusercontent.com/37429029/196156415-64be2b01-c215-4776-8e5e-8c25ef10a69c.png)
右边那一排图标感觉有些偏右了，或许可以向左挪挪

**Comment by yuyuyu-github** [comment]
中间有一个空挡

**Comment by Zuoqiu-Yingyi** [comment]
> ![image](https://user-images.githubusercontent.com/37429029/196156415-64be2b01-c215-4776-8e5e-8c25ef10a69c.png) 右边那一排图标感觉有些偏右了，或许可以向左挪挪,中间有一个空挡

可以更新一下主题, 现在工具栏是浮动的了,可以自定义位置

**Comment by git-zxx** [comment]
更新了软件和主题，现在浮动功能好像有点小bug，只要把他拖到窗口顶栏上，就再也动不了了，鼠标移动到上面也没反应,，只能重启或刷新来解决

https://user-images.githubusercontent.com/42286494/196317392-c5e9759b-c210-4020-9730-6715f4bde652.mp4
