### ISSUE TITLE
1.3.5版本，扩展功能双击后无法选中

### ISSUE THREAD

**Issue by Lyn6969** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#123]
![image](https://user-images.githubusercontent.com/42564665/196221384-f66df0d1-3aaa-4f04-8577-4ebca168d033.png)

**Comment by Lyn6969** [comment]
变成一个长条了

**Comment by Zuoqiu-Yingyi** [comment]
思源版本是?

**Comment by Zuoqiu-Yingyi** [comment]
> > 思源版本是?
> 
> 2.4.1

我这里没啥问题呀👀
要不你从仓库拉一下试试?

**Comment by Lyn6969** [comment]
> > > 思源版本是?
> > 
> > 
> > 2.4.1
> 
> 我这里没啥问题呀👀 要不你从仓库拉一下试试?

好的，我是从集市更新的，我明天试一下

**Comment by Lyn6969** [comment]
![image](https://user-images.githubusercontent.com/42564665/196387999-f9873ecc-40d6-46bc-bc40-6f4ef86f4145.png)
我重新拉了一下，好像还是不太行，而且图标也变大了

**Comment by Lyn6969** [comment]
按住也无法拖动，我卸载重装一下试试

**Comment by Lyn6969** [comment]
重装之后就好了
