### ISSUE TITLE
扩展工具栏图标问题

### ISSUE THREAD

**Issue by Hyd19** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#124]
![image](https://user-images.githubusercontent.com/84370053/196829214-3cb46979-3ae6-4b45-820c-ead0af5eaa43.png)
上图单击后，覆盖设置键 ：
![image](https://user-images.githubusercontent.com/84370053/196829286-23880e7d-1c2d-4b75-8fe4-f84bad0dd8e6.png)
任意拖动后，再点击图标拖动或双击，都失效了，变成了移动窗口或缩小窗口：
![image](https://user-images.githubusercontent.com/84370053/196829369-0210c744-8e31-4281-96f0-a26697149e7d.png)
已经在集市卸载重装过了，v1.3.5。

**Comment by Hyd19** [comment]
只要单击一次，图标周边就一直是红框，鼠标移开也一样。

**Comment by Zuoqiu-Yingyi** [comment]
下个版本会优化一下~
