### ISSUE TITLE
特性请求：能否考虑增加图片、表格的交叉引用，类似word里的插入题注和交叉引用功能

### ISSUE THREAD

**Issue by zwb709213019** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#125]
插入题注，其实已经可以提供对文档添加 auto-num-f 和 auto-num-t 属性来实现。
交叉引用，理论上可以通过复制图片的块超链接，粘贴到正文的图号中完成引用，但是在正文描述图片的时候，正文里的图号没法随着图片图号的更新而更新。

比如在图2的前文增加一张图后，原来的图2变成图3了，但正文中的图2还是没有变化。

希望可以考虑~谢谢
（或者有实现办法，希望指教！再次感谢）

**Comment by Zuoqiu-Yingyi** [comment]
这个不太行, 因为图片的自动编号纯粹是使用样式实现的, 无法实现具体逻辑
不过可以试试为被引用的图片/表格所在块添加块属性`命名`, 然后引用设置为动态锚文本, 这样修改命名时可以自动更新引用的锚文本了

**Comment by zwb709213019** [comment]
> 这个不太行, 因为图片的自动编号纯粹是使用样式实现的, 无法实现具体逻辑 不过可以试试为被引用的图片/表格所在块添加块属性`命名`, 然后引用设置为动态锚文本, 这样修改命名时可以自动更新引用的锚文本了

哦哦，明白了，还是谢啦，我研究研究~
