### ISSUE TITLE
新窗口关不掉

### ISSUE THREAD

**Issue by winter60** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#128]
有时候，打开新打开的窗口关不掉。比如我用挂件打开在资源窗口

![screenshots](https://user-images.githubusercontent.com/23653326/196867853-e16cfa84-bc14-4d2a-be50-07a30c5c0719.gif)

**Comment by winter60** [comment]
复现情况，只要在drawio里面使用过鼠标拖动，就关不了了

**Comment by winter60** [comment]
> 

同时，dark+的一些快捷键也失效。比如ctrl+F5

**Comment by Zuoqiu-Yingyi** [comment]
> 复现情况，只要在drawio里面使用过鼠标拖动，就关不了了

关闭事件被 draw.io 捕获了, 通过 draw.io 的菜单>文件>关闭>放弃更改 后才能关闭窗口

**Comment by Zuoqiu-Yingyi** [comment]
> 同时，dark+的一些快捷键也失效。比如ctrl+F5

按键事件也被 draw.io 捕获了, 鼠标焦点离开挂件才可以正常使用快捷键
