### ISSUE TITLE
新版本还能用用户自定义主题吗

### ISSUE THREAD

**Issue by jabobian** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#131]
之前是在自己的主题（Daylight+，就是系统默认主题加上Dark+的功能）里面引用了 Dark+主题的文件，工具栏是显示在标题栏上的。
今天更新了Dark+主题后，发现增强工具栏现在是浮动式的，在我自己的主题上不能显示了，必须切换到Dark+主题，双击才能显示工具栏。有什么办法可以结合用户自己的主题和Dark+功能？

**Comment by Zuoqiu-Yingyi** [comment]
可能需要引用加载一下 `/appearance/themes/Dark+/style/module/element.css` 样式文件

**Comment by jabobian** [comment]
另外，有没有可能让工具栏可以配置成始终是竖列排布，我看窗体两边的空白正好可以使用。
现在是水平布局，拖到两边都不能正常显示。

**Comment by Zuoqiu-Yingyi** [comment]
> 另外，有没有可能让工具栏可以配置成始终是竖列排布，我看窗体两边的空白正好可以使用。 现在是水平布局，拖到两边都不能正常显示。

在 [`conf\appearance\themes\Dark+\style\module\element.css`](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/blob/75a01a430cc97e2637cef36e7306bfb612bf133e/style/module/element.less#L45) 中定义

**Comment by Zuoqiu-Yingyi** [comment]
@jabobian 我这里没问题
![思源笔记-功能示范-35](https://user-images.githubusercontent.com/49649786/197316180-508d56eb-865b-4151-8901-d51f955b32d4.gif)
