### ISSUE TITLE
标签搜索的时候，长标签截断一下，露出×按钮

### ISSUE THREAD

**Issue by Geo123abc** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#132]
有一个比较长的标签，点击这个标签，调出标签搜索面板的时候，如果宽度不够，关闭的×按钮就不能看到，需要调整宽度才能出现

能否改进一下，保证搜索时，×按钮能一直有

![](https://s3.bmp.ovh/imgs/2022/10/22/558838dddd43036a.png)

**Comment by Zuoqiu-Yingyi** [comment]
使用 Shift + 滚轮可以横向滚动

**Comment by Geo123abc** [comment]
> 使用 Shift + 滚轮可以横向滚动

这是一个方案，谢谢
