### ISSUE TITLE
MAC系统下软件在非全屏幕显示时，Mac系统的窗口选项与软件部分按钮重叠

### ISSUE THREAD

**Issue by yexsi** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#133]
MAC系统版本：Ventura 13.0 (22A380)
软件版本：MAC ARM 64 2.4.5
主题版本：1.3.5
问题描述：MAC系统下软件在非全屏幕显示时，Mac系统的窗口选项与软件部分按钮重叠
<img width="1918" alt="image" src="https://user-images.githubusercontent.com/63133923/197399289-0e8fd461-daa3-4118-baab-1f4c234849fe.png">
软件全屏幕显示后，则不冲突
<img width="1919" alt="image" src="https://user-images.githubusercontent.com/63133923/197399332-019bf167-4c33-41ef-9818-ae0b3a655a4a.png">
<img width="1919" alt="image" src="https://user-images.githubusercontent.com/63133923/197399245-d82c885e-4d6f-47ad-a44d-8ea4641b7528.png">

**Comment by Zuoqiu-Yingyi** [comment]
默认主题下是什么样子的❓

**Comment by yexsi** [comment]
默认主题显示正常
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/63133923/197401178-d255c917-894b-41b4-a572-89cb624f4853.png">

**Comment by Zuoqiu-Yingyi** [comment]
嗯嗯, 能打开开发者模式瞅瞅左上角对应元素的具体样式嘛, 我没有测试设备, 只能尝试兼容了~

**Comment by yexsi** [comment]
请问提供这些是否足够呢？
<img width="1920" alt="默认主题左上角" src="https://user-images.githubusercontent.com/63133923/197402152-b48e32bf-cbf0-4c47-88db-d9a410e81ecd.png">
[默认主题样式css.txt](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/files/9846967/css.txt)
