### ISSUE TITLE
萌新有考虑在b站投稿一些演示视频之类的吗？

### ISSUE THREAD

**Issue by yuyuyu-github** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#135]
不知道萌新是否在B站有号，我搜了颖逸没搜着。😂
虽然ZYF大佬出了一期讲dark+主题的，但还是比较浅，过了3、4个主要的功能。
![image](https://user-images.githubusercontent.com/37429029/197550229-b64dc6ec-3dbd-4ae1-bc37-29d4ffde9cc2.png)
或许萌新自己可以在b站出一个dark+主题的教学视频、挂件块分享，还有后面可能有的插件分享。
还有思源自带功能，例如sql块的使用技巧（这个ZYF说要出结果一直没出＞︿＜）。 还有思源和其他工具联动的工作流。
这些方面你都是专家级别的了，肯定可以吸一波粉。
当然知道萌新现在研一很忙，只是提个想法。
要是后面会在B站投稿视频，我肯定给你一键三连ヾ(≧▽≦*)o

**Comment by Zuoqiu-Yingyi** [comment]
没制作过视频, 而且好日子过完后就忙起来了...

**Comment by yuyuyu-github** [comment]
> 没制作过视频, 而且好日子过完后就忙起来了...

收到
