### ISSUE TITLE
v2.4.5把几个按钮搬到右边，挤占了dark+扩展工具栏的位置，现在扩展工具栏即不能在标题栏上展开，也无法拖到到其他位置

### ISSUE THREAD

**Issue by wildfire945** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#136]
v2.4.5把几个按钮搬到右边，挤占了dark+扩展工具栏的位置，现在扩展工具栏即不能在标题栏上展开，也无法拖到到其他位置（指向扩展工具栏按钮时有按住拖动的提示，但怎么都拖不动），请问能不能解决一下，谢谢
![7L%KX9 67FH2WESHBJ03K 7](https://user-images.githubusercontent.com/116587395/197587057-8ee5f337-6dfe-4c1e-a5a1-d6c8c8852c9b.png)

**Comment by Zuoqiu-Yingyi** [comment]
禁用缓存后刷新试试

**Comment by wildfire945** [comment]
请问如何禁用缓存呢，我在软件设置里面没有找到，多谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Zuoqiu-Yingyi/siyuan-theme-dark-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月25日(星期二) 凌晨1:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Zuoqiu-Yingyi/siyuan-theme-dark-plus] v2.4.5把几个按钮搬到右边，挤占了dark+扩展工具栏的位置，现在扩展工具栏即不能在标题栏上展开，也无法拖到到其他位置 (Issue #136)





 
禁用缓存后刷新试试

**Comment by Zuoqiu-Yingyi** [comment]
请参考: https://publish.zuoqiu.space/block/20200922102318-oz84yu3?id=20201225202158-gfmyvql

**Comment by wildfire945** [comment]
已经禁用并且刷新了，但是扩展工具栏还是没法展开

**Comment by Zuoqiu-Yingyi** [comment]
> 已经禁用并且刷新了，但是扩展工具栏还是没法展开

能拖动了吗?

**Comment by wildfire945** [comment]
无论双击扩展按钮前后都拖不动，您的回复好快，谢谢

**Comment by Zuoqiu-Yingyi** [comment]
@wildfire945 那么开启随机端口试试, 可能缓存没有清理干净
