### ISSUE TITLE
工具栏展开异常

### ISSUE THREAD

**Issue by AugustTuan** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#137]
![QQ截图20221026082529](https://user-images.githubusercontent.com/37429029/197906356-90efdb8e-dc43-410c-a2f9-6ac55009aa2c.png)

**Comment by yuyuyu-github** [comment]
更新到了最新版

**Comment by Zuoqiu-Yingyi** [comment]
禁用缓存后刷新试试
