### ISSUE TITLE
能否加入自带的日历面板

### ISSUE THREAD

**Issue by yuyuyu-github** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#138]
现在notion主题支持了
![QQ截图20221026082557](https://user-images.githubusercontent.com/37429029/197906491-cb464a71-58f7-4bf4-89a7-7236e3a8c291.png)

**Comment by Zuoqiu-Yingyi** [comment]
我试了一下, 感觉没啥用呀😂

**Comment by yuyuyu-github** [comment]
> 我试了一下, 感觉没啥用呀😂

可以浏览不同日期的日记。比翻文档树还是舒服点的(。・ω・。)

**Comment by Zuoqiu-Yingyi** [comment]
> > 我试了一下, 感觉没啥用呀😂
> 
> 可以浏览不同日期的日记。比翻文档树还是舒服点的(。・ω・。)

可以试试 `Daily Views` 挂件

**Comment by yuyuyu-github** [comment]
> > > 我试了一下, 感觉没啥用呀😂
> > 
> > 
> > 可以浏览不同日期的日记。比翻文档树还是舒服点的(。・ω・。)
> 
> 可以试试 `Daily Views` 挂件

好的
