### ISSUE TITLE
v0.7.3 版本思维导图模式有时无效

### ISSUE THREAD

**Issue by clark874** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#14]
感谢作者的工作！
在笔记的列表中尝试使用思维导图模式，发现没有变化。相反列表模式可以操作。
<img width="380" alt="image" src="https://user-images.githubusercontent.com/86122040/164030842-3f172b14-ca63-431f-bde6-66a1de84576a.png">

**Comment by Zuoqiu-Yingyi** [comment]
> 感谢作者的工作！ 在笔记的列表中尝试使用思维导图模式，发现没有变化。相反列表模式可以操作。 <img alt="image" width="380" src="https://user-images.githubusercontent.com/86122040/164030842-3f172b14-ca63-431f-bde6-66a1de84576a.png">

是的, 因为 CSS 样式优先级问题, 目前只能支持在列表块/文档块/引述块/超级块/嵌入块中设置思维导图模式

不过建议升级一下主题版本至 `v0.8.2+` (应该明天上午就能更新了), 可以通过块菜单非常方便的转换列表视图

**Comment by clark874** [comment]
> 

上一次表述我没说清楚，我的意思是：
* 1

  * 2

    * 3
这类的列表块，可以通过菜单转换为表格，但无法转换为思维导图。

**Comment by Zuoqiu-Yingyi** [comment]
> > 
> 
> 上一次表述我没说清楚，我的意思是：
> 
> * 1
>   
>   * 2
>     
>     * 3
>       这类的列表块，可以通过菜单转换为表格，但无法转换为思维导图。

先更新一下 Dark+ 版本试试
![image](https://user-images.githubusercontent.com/49649786/164183711-9ebb2cd9-5d18-4b4d-be66-6575fbc7562f.png)

**Comment by clark874** [comment]
我更新了最新版，录了一个视频，问题还是存在

https://user-images.githubusercontent.com/86122040/164186727-160c91a8-61b5-4d25-bb87-7a96cdf63447.mp4

：

**Comment by Zuoqiu-Yingyi** [comment]
> 我更新了最新版，录了一个视频，问题还是存在
> 
>  ScreenFlow.mp4 
> ：

最新版是 `v0.8.2`, 集市应该刚刚更新, 再升级一次试试

**Comment by clark874** [comment]
> 

这次可以了，感谢作者！
