### ISSUE TITLE
更新后暗色主题在浏览器不生效

### ISSUE THREAD

**Issue by jhzerone** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#143]
暗色主题在浏览器不生效了, 有个脚本错
![image](https://user-images.githubusercontent.com/58368113/198234720-511f9f5f-9f22-42a5-8b91-123f221f0637.png)

**Comment by Zuoqiu-Yingyi** [comment]
为啥我这里暗色主题与脚本均没问题👀❓

**Comment by jhzerone** [comment]
我是从集市直接更新的, 是不是有什么问题需要清理?

**Comment by Zuoqiu-Yingyi** [comment]
> 我是从集市直接更新的, 是不是有什么问题需要清理?

禁用缓存后刷新试试?

**Comment by jhzerone** [comment]
已经disabled cache 和 使用 ctrl+shift+R 刷新的

**Comment by Zuoqiu-Yingyi** [comment]
> 已经disabled cache 和 使用 ctrl+shift+R 刷新的

那对比一下浏览器中加载的 `conf\appearance\themes\Dark+\script\utils\dom.js` 文件与原文件是否有差别

**Comment by jhzerone** [comment]
谢谢, 这边重新再点了一次更新后正常了, 可能前一次更新有问题,
