### ISSUE TITLE
工具栏与顶部标题重合

### ISSUE THREAD

**Issue by yuyuyu-github** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#144]
虽然工具栏可以悬浮，但是最省空间、常用的方式，还是横着放在顶部。
但是有两个问题：
1. 工具栏图标会和顶部的标题发生重叠，希望可以遮挡掉顶部的标题
2. 工具栏没有办法和右边的系统图标对齐。
![QQ截图20221026171041](https://user-images.githubusercontent.com/37429029/198296378-4b1762e6-f21a-4cd8-9024-7d120f158cc1.png)

**Comment by Zuoqiu-Yingyi** [comment]
1. 不能覆盖, 因为顶部标题也是系统窗口的标题栏, 用于拖动(可以试试放在底部状态栏或者左右边栏)
2. 我这里是和系统图标对齐的 <img width="396" alt="image" src="https://user-images.githubusercontent.com/49649786/198300246-34077c46-f1fc-4188-919e-7ea24ff4eee2.png">

**Comment by yuyuyu-github** [comment]
好的，收到🫡
