### ISSUE TITLE
设定页签最小宽度后，关闭按钮位置未居右

### ISSUE THREAD

**Issue by Hyd19** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#145]
![image](https://user-images.githubusercontent.com/84370053/198422665-56002a12-d14e-4dbb-94b1-1a4a575a136f.png)
照理应贴右？

**Comment by Zuoqiu-Yingyi** [comment]
试试设置页签中文本的最小宽度？

**Comment by Hyd19** [comment]
> 试试设置页签中文本的最小宽度？
没找到这个设置啊。以前这么设置是没问题的，关闭键都是靠最右，从默认主题改版就这样了。

**Comment by Zuoqiu-Yingyi** [comment]
> 没找到这个设置啊。以前这么设置是没问题的，关闭键都是靠最右，从默认主题改版开始就这样了。

我也没找到 `设定页签最小宽度` 这个设置呀❓

**Comment by Hyd19** [comment]
> 文本

好吧，全称叫“非钉住页签项最小宽度”。。。
![image](https://user-images.githubusercontent.com/84370053/198500610-aa27edbd-c4cb-4616-82c4-0bacc7c8f3ad.png)
