### ISSUE TITLE
请求Jupyter支持密码验证

### ISSUE THREAD

**Issue by crafter-z** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#146]
Jupyter使用cookie我完全连不上去，但是Token可以。然而每次重新启动Jupyter的时候Token都会变，想要再用还得改token很麻烦，是否可以考虑支持Juyper的密码登陆？

**Comment by Zuoqiu-Yingyi** [comment]
> Jupyter使用cookie我完全连不上去，但是Token可以。然而每次重新启动Jupyter的时候Token都会变，想要再用还得改token很麻烦，是否可以考虑支持Juyper的密码登陆？

因为 Jupyter 服务有跨域限制, 目前我还没找到链接非本机服务的解决方案
Token 可以通过设置 `c.ServerApp.token` 或者 `c.NotebookApp.token` 字段设置一个固定的值

**Comment by crafter-z** [comment]
好吧……这样的话暂时只能拿Token当密码用了:(
