### ISSUE TITLE
2.4.7使用dark++主题没有显示换背景的按钮。。。

### ISSUE THREAD

**Issue by qing-root** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#147]
如题：

![image](https://user-images.githubusercontent.com/30001685/198946443-52f0bfde-9a49-4aa9-a49f-a1144177dd5e.png)

**Comment by Zuoqiu-Yingyi** [comment]
改成悬浮工具栏啦, 可以试试拖动右上角的的按钮
