### ISSUE TITLE
滚屏显示可以支持自定义拉伸滚屏区域的长度吗？

### ISSUE THREAD

**Issue by yuyuyu-github** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#148]
不知道现不现实。 想要上下拉伸/收窄滚屏显示的区域
![image](https://user-images.githubusercontent.com/37429029/199227659-6989ff31-709f-4c10-8225-a8eddff6a147.png)

**Comment by Zuoqiu-Yingyi** [comment]
使用 CSS 变量 `--custom-scroll-max-height` 自定义该区域的最大高度

**Comment by yuyuyu-github** [comment]
好的
