### ISSUE TITLE
评论面板上文字不能选中

### ISSUE THREAD

**Issue by Brief-su** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#150]
对一段文字进行评论，然后双击该评论，弹出评论面板，无法在评论面板上选中任何文字，面板会在鼠标选中一瞬间关闭
![image](https://user-images.githubusercontent.com/60416974/199482641-245482ad-5bc2-4486-bf35-51c8d5a0be4b.png)

**Comment by Zuoqiu-Yingyi** [comment]
在这里反馈一下吧: [Issues · langzhou/siyuan-note](https://github.com/langzhou/siyuan-note/issues)

**Comment by Brief-su** [comment]
好嘞，谢谢你



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月2日(星期三) 晚上8:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Zuoqiu-Yingyi/siyuan-theme-dark-plus] 评论面板上文字不能选中 (Issue #150)





 
在这里反馈一下吧: Issues · langzhou/siyuan-note
