### ISSUE TITLE
Dark+的旗帜emoji显示不全的问题

### ISSUE THREAD

**Issue by sq98** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#151]
思源默认主题是全支持emoji的，问题是：
1.Dark+主题的文档树里的Twitter emoji是全支持的显示的，但使用原生系统emoji时，旗帜emoji 和一些 符号emoji 是显示不全的。
2.Dark+主题 在编辑区里的 旗帜emoji 在任何情况下都几乎是不支持显示的。可否修复这两个问题，感谢，加油。

本人使用的是Mac版思源笔记v2.4.9，Dark+ v1.3.7。
![image](https://user-images.githubusercontent.com/11554027/199867643-7d6c6362-d815-4919-bce0-7fdd3908e48b.png)

**Comment by Zuoqiu-Yingyi** [comment]
@tswwe 这应该是由于当前使用的字体没有这些 emoji 字符导致的
如果切换为默认主题依旧不显示或者更换字体后显示, 应该就是这个原因

**Comment by sq98** [comment]
是的，当设置为除默认字体以外的字体后，emoji包括旗帜都全部显示正常了(虽然样式改变了)，这是一个暂时可用的方法。不过大佬这个问题目前不打算修复吗？还是无法修复呢？(如上图那样的emoji样式挺好看的，很喜欢)

**Comment by Zuoqiu-Yingyi** [comment]
应该可以使用自定义的字体列表设置 emoji, 但是我也没具体研究过
