### ISSUE TITLE
从别的位置粘贴的图片，粘贴到dark+，图片就变成了黑色，特别不好识别

### ISSUE THREAD

**Issue by AugustTuan** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#155]
粘贴的图片喝复制的图片不一样，变得乌漆嘛黑的
![image](https://user-images.githubusercontent.com/117956441/201305597-d8ab24ae-828b-4127-8ddb-449ad620c351.png)

![image](https://user-images.githubusercontent.com/117956441/201305646-d58bd425-5ab5-48a9-a4b0-c5bceb1193c5.png)

**Comment by Zuoqiu-Yingyi** [comment]
请检查 `反色显示` 功能是否开启

**Comment by AugustTuan** [comment]
原来如此，谢谢。 我看那个图标还以为是黑夜模式😂
