### ISSUE TITLE
工具栏支持将不常用的按钮折叠起来，只展示常用按钮

### ISSUE THREAD

**Issue by Yuminis98** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#156]
Dark+由于功能按钮特别多，是现在集市里面，唯一一个工具栏无法很好的放在顶栏的主题

![image](https://user-images.githubusercontent.com/117956441/201466466-b424a184-af00-4dcb-83c2-7037df69821a.png)

我尝试了把工具栏放在右上角，或者放在底栏， 都特别奇怪，还会遮挡正文。
并且如果只是在dark+把工具栏放在底部，那么习惯了这种操作模式，切换成别的主题也就需要跟着更改使用习惯。

dark+顶部的按钮虽然很多，但是一般都会分为几个很常用的按钮，和一些平常不怎么使用的按钮，
比如切换图片、在新窗口打开这些，我用主题快一年了，完全不会或者很少会使用这几个按钮，让这些按钮一直占据着顶部中间的C位，实在是暴殄天物。
![image](https://user-images.githubusercontent.com/117956441/201466578-8ff85e64-e561-4e47-89ae-a0a6b7c2f953.png)

**能否支持用户将一些很少使用的按钮隐藏到一个按钮下面，或者将工具栏分成两页，放置到第二页去。**

如果只把自己平常会用到的按钮显示出来的话，右半边这部分空间就已经绰绰有余了，真的。

 那么工具栏就和其他主题一样，可以正常放置在顶栏，也不会和顶部标题重合啦。

而且图标比较少的好处，就是映入眼帘的按钮少，而且都是经常用的，点击按钮不用每次都找一下。
![Snipaste_2022-11-12_16-42-36](https://user-images.githubusercontent.com/117956441/201466420-e0d6d587-56a7-4508-94cb-fba6bf93444b.png)

**Comment by Yuminis98** [comment]
希望萌新大大考虑
![Suggestion](https://user-images.githubusercontent.com/117956441/201466868-4868c261-ef3e-432a-a31e-70d890268e0b.gif)

**Comment by Zuoqiu-Yingyi** [comment]
每个按钮都在配置文件有个是否显示的属性👀

**Comment by Yuminis98** [comment]
> 每个按钮都在配置文件有个是否显示的属性👀

真的！！配置文件在哪里，我找了半天没找着

**Comment by Zuoqiu-Yingyi** [comment]
`\script\module\config.js`
不过不建议直接修改, 而是使用 `custom.js` 覆盖指定的字段
自述文件有教程
