### ISSUE TITLE
Drak+在窗口向下还原后，图标会产生大量地重叠。

### ISSUE THREAD

**Issue by Yuminis98** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#157]
因为我是英语专业的，对开发完全一窍不通。那个配置我一直没弄明白就放弃了。

虽然工具栏放在顶部会有和顶部标题重合的问题，但是我觉得可以接受，所以继续这么使用了。

但是最近又发现了另外一个问题，就是如果选择右上角的【向下还原】，窗口缩小一点以后，右边这一排图标就全都叠在一块了。

![image](https://user-images.githubusercontent.com/117956441/201802783-bbe08d73-a4b5-4ac6-9fcf-7cd1dae05778.png)

**Comment by Zuoqiu-Yingyi** [comment]
双击橙色边框按钮可以折叠该图标, 叠在一起的话只能重新拖动放置在其他位置了
