### ISSUE TITLE
最新的1.5.0版本重新下载后，按照自述文件自定义背景效果不显示，依旧是原来的两张默认背景

### ISSUE THREAD

**Issue by Zting6906** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#159]
大大，最新的1.5.0版本重新下载以后，按照自述文件自定义背景后，效果不显示，依旧是原来的那两张默认背景

**Comment by Zuoqiu-Yingyi** [comment]
能发一下配置文件路径与内容嘛, 我瞅瞅是否正确❓

**Comment by Zting6906** [comment]
> 能发一下配置文件路径与内容嘛, 我瞅瞅是否正确❓

噢噢，图片在这里，大大救命😭
![Z R)~E8UX_TV2MZ7@K8}TWW](https://user-images.githubusercontent.com/84259169/202516668-ff9fd7e1-1e79-4984-9f94-79026fd2038a.png)

**Comment by Zting6906** [comment]
> 能发一下配置文件路径与内容嘛, 我瞅瞅是否正确❓

![image](https://user-images.githubusercontent.com/84259169/202516857-1194127b-1f84-4e50-9eda-7f8624c24565.png)
![image](https://user-images.githubusercontent.com/84259169/202516965-d8f55f48-0a98-4f81-b09e-e80fa16c4689.png)

**Comment by moon4869** [comment]
+1，更新最新思源版本后自定义的背景图片失效了，前面版本都有效的，是自定义custom.js里面放图片路径的方式做的

**Comment by Zuoqiu-Yingyi** [comment]
@moon4869 @Zting6906 哦哦, `v1.5.0` 竖屏与横屏分别设置了不同的背景图片, 试试用
`data/widgets/custom-light.css` 与 `data/widgets/custom-dark.css` 文件设置背景图片
文件内容如下
```css
:root {
    --custom-background-image: url("your/background/image/path.ext");
}

```

**Comment by Zting6906** [comment]
> @moon4869 @Zting6906 哦哦, `v1.5.0` 竖屏与横屏分别设置了不同的背景图片, 试试用 `data/widgets/custom-light.css` 与 `data/widgets/custom-dark.css` 文件设置背景图片 文件内容如下
> 
> ```css
> :root {
>     --custom-background-image: url("your/background/image/path.ext");
> }
> ```

ok，我现在试试哈哈

**Comment by Zting6906** [comment]
> @moon4869 @Zting6906 哦哦, `v1.5.0` 竖屏与横屏分别设置了不同的背景图片, 试试用 `data/widgets/custom-light.css` 与 `data/widgets/custom-dark.css` 文件设置背景图片 文件内容如下
> 
> ```css
> :root {
>     --custom-background-image: url("your/background/image/path.ext");
> }
> ```

萌大，这个新的试了一下没效果，然后自述文件里原先的那个custom-dark.css文件，里面的内容是`:root {
    /* 深色主题默认背景图片 | default background image for dark color theme */
    --custom-background-image: url("/widgets/background-dark.png");

    /* 深色主题默认对话框背景图片 | default dialog background image for dark color theme */
    --custom-background-image-dialog: url("/widgets/background-dark-dialog.png");
}`
原先的这个custom-dark.css试了一下，对话框背景换了，但是主体背景依旧是默认的那两张。

新的custom-dark.css和旧的custom-dark.css试了都没效果。

**Comment by Zuoqiu-Yingyi** [comment]
> 新的custom-dark.css和旧的custom-dark.css试了都没效果。

@Zting6906 试试打开开发者模式后使用快捷键 <kbd>Ctrl + F5</kbd> 刷新, 可能命中了缓存的旧配置文件

**Comment by Zting6906** [comment]
> ```css
> your/background/image/path.ext
> ```

![image](https://user-images.githubusercontent.com/84259169/202696684-340df815-f8b5-4965-8952-2fa221915f67.png)
我不是很懂代码，这个路径path是不是要换成什么具体的文件路径😂

**Comment by Zuoqiu-Yingyi** [comment]
> > ```css
> > your/background/image/path.ext
> > ```
> 
> ![image](https://user-images.githubusercontent.com/84259169/202696684-340df815-f8b5-4965-8952-2fa221915f67.png) 我不是很懂代码，这个路径path是不是要换成什么具体的文件路径😂

对于你放在 `assets/images/background-dark/` 目录下的 `background-1.png` 图片来说就是
```css
:root {
    --custom-background-image: url("assets/images/background-dark/background-1.png");
}
```

**Comment by Zting6906** [comment]
> > > ```css
> > > your/background/image/path.ext
> > > ```
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/84259169/202696684-340df815-f8b5-4965-8952-2fa221915f67.png) 我不是很懂代码，这个路径path是不是要换成什么具体的文件路径😂
> 
> 对于你放在 `assets/images/background-dark/` 目录下的 `background-1.png` 图片来说就是
> 
> ```css
> :root {
>     --custom-background-image: url("/assets/images/background-dark/background-1.png");
> }
> ```

![image](https://user-images.githubusercontent.com/84259169/202699636-f4217288-994c-40b4-a220-d566056754d3.png)
我重新试了一下，新增custom-dark后，并且当这个js文件删掉后，重新刷新，我设置的主题背景就能显示出来了，但是一按更换背景图片里面没有我设置的；这个js文件在的时候，我刷新、禁用缓存重进什么的，都没办法显示我设置的背景图片😂

**Comment by Zuoqiu-Yingyi** [comment]
> ![image](https://user-images.githubusercontent.com/84259169/202699636-f4217288-994c-40b4-a220-d566056754d3.png) 我重新试了一下，新增custom-dark后，并且当这个js文件删掉后，重新刷新，我设置的主题背景就能显示出来了，但是一按更换背景图片里面没有我设置的；这个js文件在的时候，我刷新、禁用缓存重进什么的，都没办法显示我设置的背景图片😂

这是因为 `v1.5.0` 版本横屏与竖屏使用了不同的背景图片, 不过好像忘了修改 README 中的教程😂
刚刚更新了一下: https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus#customjs

**Comment by moon4869** [comment]
> > ![image](https://user-images.githubusercontent.com/84259169/202699636-f4217288-994c-40b4-a220-d566056754d3.png) 我重新试了一下，新增custom-dark后，并且当这个js文件删掉后，重新刷新，我设置的主题背景就能显示出来了，但是一按更换背景图片里面没有我设置的；这个js文件在的时候，我刷新、禁用缓存重进什么的，都没办法显示我设置的背景图片😂
> 
> 这是因为 `v1.5.0` 版本横屏与竖屏使用了不同的背景图片, 不过好像忘了修改 README 中的教程😂 刚刚更新了一下: https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus#customjs

按照最新的教程，更新设置之后成功啦，原来不行的时候连切换背景图片的两个按钮都没了😂😂，我还以为新版本不支持了

**Comment by Zting6906** [comment]
> > ![image](https://user-images.githubusercontent.com/84259169/202699636-f4217288-994c-40b4-a220-d566056754d3.png) 我重新试了一下，新增custom-dark后，并且当这个js文件删掉后，重新刷新，我设置的主题背景就能显示出来了，但是一按更换背景图片里面没有我设置的；这个js文件在的时候，我刷新、禁用缓存重进什么的，都没办法显示我设置的背景图片😂
> 
> 这是因为 `v1.5.0` 版本横屏与竖屏使用了不同的背景图片, 不过好像忘了修改 README 中的教程😂 刚刚更新了一下: https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus#customjs

萌佬，你坏事做尽😂😂


现在重新按照教程配置了，完美解决。
萌佬今天也辛苦了，感谢🙏🙏

**Comment by Zting6906** [comment]
> > > ![image](https://user-images.githubusercontent.com/84259169/202699636-f4217288-994c-40b4-a220-d566056754d3.png) 我重新试了一下，新增custom-dark后，并且当这个js文件删掉后，重新刷新，我设置的主题背景就能显示出来了，但是一按更换背景图片里面没有我设置的；这个js文件在的时候，我刷新、禁用缓存重进什么的，都没办法显示我设置的背景图片😂
> > 
> > 
> > 这是因为 `v1.5.0` 版本横屏与竖屏使用了不同的背景图片, 不过好像忘了修改 README 中的教程😂 刚刚更新了一下: https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus#customjs
> 
> 按照最新的教程，更新设置之后成功啦，原来不行的时候连切换背景图片的两个按钮都没了😂😂，我还以为新版本不支持了

ok，谢谢你的提醒，我重新配置也成功了哈哈✌
