### ISSUE TITLE
希望列表转表格的时候，嵌入块可以以单独一列而不是多列的形式展示~

### ISSUE THREAD

**Issue by 1995hanjian** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#16]
![image](https://user-images.githubusercontent.com/39188734/164182928-07ddec52-7c3e-4ef1-bf0e-1ed52d357b7e.png)
![image](https://user-images.githubusercontent.com/39188734/164182992-24eb4703-d07e-484f-8485-8896c418c60f.png)

如题~
嵌入块如果在表格里，分成多列的话就有点看不清楚了~
求大佬帮忙改一改~~

**Comment by Zuoqiu-Yingyi** [comment]
[feat: 列表表格视图与脑图视图内列表项中嵌入块保持纵向排列](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/commit/7be173b0a6cbadeb931445ce566ca7d53caff887)
