### ISSUE TITLE
question: 使用dark+的浮动工具栏，除了引用theme.js还要引用什么呢？

### ISSUE THREAD

**Issue by winter60** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#160]
萌佬好，现在我在代码片段中引用了dark+的theme.js，但是其他主题不能像dark+主题一样拖动和自适应扩展工具栏。在想是不是还要引入其他的css或js。

**Comment by Zuoqiu-Yingyi** [comment]
还需要引用 `conf\appearance\themes\Dark+\style\module\element.css` 样式文件

**Comment by winter60** [comment]
谢谢萌佬啦，除了`element.css`好像还要`@import url('/appearance/themes/Dark+/style/config/config.css')`才行，虽然有图标有点点没有居中，不过不影响。
![image](https://user-images.githubusercontent.com/23653326/202735426-8f4b73fc-8cf4-425f-8edb-38f8fa44027b.png)

**Comment by Zuoqiu-Yingyi** [comment]
图标样式在 `bar.css` 里面
