### ISSUE TITLE
求教：遇到光标在超链接后面直接Shift-Enter硬回车无反应，需要添加空格

### ISSUE THREAD

**Issue by jabobian** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#161]
Yingyi好，我经常遇到光标在超链接后面直接Shift-Enter硬回车无反应，需要添加空格才能完成。
但是貌似只要完成一次完整的Shift-Enter之后，会有一段时间没有问题。

一种情况是用了 Shift+Numpad上的Enter，会影响后面一次 Shift+Enter。

**Comment by Zuoqiu-Yingyi** [comment]
思源更新至 `v2.5.1` 试试, 我在该版本无法复现, 可能随着一个相关的 bug 一起修复了
REF: [光标位于列表项末尾的行内公式后时回车表现异常 · Issue #6679 · siyuan-note/siyuan](https://github.com/siyuan-note/siyuan/issues/6679)

**Comment by Zuoqiu-Yingyi** [comment]
我先关闭了, 如何还能复现我再打开修复
