### ISSUE TITLE
导出的背景问题

### ISSUE THREAD

**Issue by SuperNoobTao** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#163]
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/16486344/204534113-a882c669-a1c0-420b-85bf-860f5abe5b44.png">

<img width="1345" alt="image" src="https://user-images.githubusercontent.com/16486344/204533460-21025eaf-8273-43f8-8133-e451accd4bac.png">
mac系统，在明亮主题下导出是这样的，有一个网格的背景。。不知道这是不是我使用有问题呀，希望作者大大有空解答一下～

然后深色主题下导出，选项栏看不到东西了。。
<img width="1201" alt="image" src="https://user-images.githubusercontent.com/16486344/204534361-aee64469-42f3-495b-917d-17e22708313b.png">

**Comment by Zuoqiu-Yingyi** [comment]
在 [6c73186](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/commit/6c73186b0e5a86d3b0ff41fc49e52a192f50daf9) 中针对导出样式进行了一些优化，可以克隆一下仓库或等下个版本再试试

**Comment by SuperNoobTao** [comment]
好的，多谢多谢🙏作者大大辛苦
