### ISSUE TITLE
:bug: 約自從思源2.3.0更新後，上方工具欄就一直沒出現

### ISSUE THREAD

**Issue by CHANGPINHSIN** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#164]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

約自思源2.3.0更新後，上方工具欄就一直沒出現，以為新版本的Dark+主題會修復，結果一直沒等到，故來此回報bug。詳如附圖：
![image](https://user-images.githubusercontent.com/66910353/205356373-11446d41-25fd-4909-9d0f-451654aab5a3.png)

### 期待的结果 Expected result

希望能再次見到此主題的上方工具欄，謝謝

### 版本环境 Version environment

```markdown
- SiYuan Version: 2.5.2
- Dark+ Version: 1.5.2
- Operating System: Windows 10
- Browser (if used):
```

**Comment by Zuoqiu-Yingyi** [comment]
有一些奇怪呀，我這裡沒法復現，目前也沒有其他人反饋該問題，要不打開開發者工具瞅瞅有無錯誤信息輸出？

**Comment by CHANGPINHSIN** [comment]
> 有一些奇怪呀，我這裡沒法復現，目前也沒有其他人反饋該問題，要不打開開發者工具瞅瞅有無錯誤信息輸出？

您好，經過測試後發現，我使用的語言是繁體中文，將語言切換成簡體中文就能出現工具列了。

**Comment by CHANGPINHSIN** [comment]
補充說明一下，在繁體中文的環境下，不只工具列無法出現，對塊按右鍵也無法看到Dark+這個主題所額外提供的功能。

**Comment by Zuoqiu-Yingyi** [comment]
@CHANGPINHSIN 感謝，已定位到錯誤，`i10n` 回退沒有處理好

**Comment by CHANGPINHSIN** [comment]
@Zuoqiu-Yingyi  太好了，讓您費心尋找問題的來源了！感激不盡！期待更新版~
