### ISSUE TITLE
:bug: 光标选择文本时，如果超出文本框范围则无法调起编辑菜单栏

### ISSUE THREAD

**Issue by EdwinWang0508** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#165]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

光标选择文本时，如果超出文本框范围则无法调起编辑菜单栏
图可见：
[ld246.com/article/1670504392992](https://ld246.com/article/1670504392992)
标题3

### 期待的结果 Expected result

能够随意框选文字并调起菜单栏，而不用刻意选择在文本框内

### 版本环境 Version environment

```markdown
- SiYuan Version: 2.5.3
- Dark+ Version: 1.5.3
- Operating System: macos13
- Browser (if used):
```

**Comment by Zuoqiu-Yingyi** [comment]
### Dark+ 主题快捷键能否通过添加 js 片段来更改
鼠标中键可以使用触摸板三指点击实现

### Block 滚动条如何关闭
使用如下 CSS 片段
```css
.protyle-scroll {
    display: none;
}
```

### 编辑工具栏 bug
这是因为开启自适应宽度后编辑器的边距太窄的原因, 可以通过关闭自适应宽度或者自定义 CSS 变量 `--custom-editor-padding-left` 与 `--custom-editor-padding-right` 改善

**Comment by EdwinWang0508** [comment]
> ### Dark+ 主题快捷键能否通过添加 js 片段来更改
> 
> 鼠标中键可以使用触摸板三指点击实现
> ### Block 滚动条如何关闭
> 
> 使用如下 CSS 片段
> 
> ```css
> .protyle-scroll {
>     display: none;
> }
> ```
> 
> ### 编辑工具栏 bug
> 
> 这是因为开启自适应宽度后编辑器的边距太窄的原因, 可以通过关闭自适应宽度或者自定义 CSS 变量 `--custom-editor-padding-left` 与 `--custom-editor-padding-right` 改善

多谢作者大大，但是我三指设置了单词查询，无法实现该功能，已用脚本模拟器代替
