### ISSUE TITLE
:sparkles: 能否添加列表转看板功能及日历按钮

### ISSUE THREAD

**Issue by EdwinWang0508** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#166]
## 1.列表转看板
方便进行进度管理
## 2.日历按钮
更方便查看日记

### 描述可能的最优解决方案 Describe the optimal solution

royc01作者已经实现了这俩种功能
calendar和list2board
附项目地址：
[royc01/notion-theme](https://github.com/royc01/notion-theme)

**Comment by Zuoqiu-Yingyi** [comment]
- [ ] #113 
- [ ] 日历按钮

**Comment by Zuoqiu-Yingyi** [comment]
日历按钮有朋友通过插件实现了, 我先关闭了👀
