### ISSUE TITLE
:bug: Dark+ 主题快捷键失效以及文档阅读位置 bug 

### ISSUE THREAD

**Issue by EdwinWang0508** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#167]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

## 右上角不显示当前阅读文档位置，且右键滚动条无法回到记录位置
gif图关联：
[ld246.com/article/1670518757398](https://ld246.com/article/1670518757398)

### 期待的结果 Expected result

1.正常使用快捷键，或便捷长效的快捷键修改方法
2.关闭页面后仍能定位阅读文档位置

### 版本环境 Version environment

```markdown
- SiYuan Version: 2.5.3
- Dark+ Version: 1.5.3
- Operating System: macos13
- Browser (if used):
```

**Comment by Zuoqiu-Yingyi** [comment]
下个版本启用记住当前位置后鼠标<kbd>双击</kbd>块会更新记住的位置为 **所双击的块**
