### ISSUE TITLE
:bug: 黑色主题标记的字被蓝色背景覆盖，完全看不见

### ISSUE THREAD

**Issue by HecterF** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#169]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

![image](https://user-images.githubusercontent.com/46716553/206828116-c32fa16a-a13b-4c33-bec8-45c1e29a22f9.png)

### 期待的结果 Expected result

![image](https://user-images.githubusercontent.com/46716553/206828129-91ca8ec7-09db-458d-981c-f6d83b1bc730.png)

### 版本环境 Version environment

```markdown
- SiYuan Version: v2.5.3
- Dark+ Version: v1.5.3
- Operating System: 
- Browser (if used):
```

**Comment by Zuoqiu-Yingyi** [comment]
这是特性, 有如下三种显示方案
1. 鼠标悬浮在标记上显示文本内容
2. 在该块或上级块设置块属性 `mark`: `display` (也可以使用扩展菜单的 `更多 > 显示标记文本` 菜单项)
3. 在悬浮工具栏中点击 `显示标记文本` 按钮

**Comment by HecterF** [comment]
> 

学习了，多谢。
