### ISSUE TITLE
如何实现在文档目录中改变标题颜色

### ISSUE THREAD

**Issue by clark874** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#17]
无意中发现目录中一篇文章的标题颜色变成红色了，不知道作者是否知道这是怎么实现的？
<img width="540" alt="2022-04-20 19 49 46" src="https://user-images.githubusercontent.com/86122040/164224127-190017c7-0cdc-44f8-9702-e43d292d65a4.png">

**Comment by Zuoqiu-Yingyi** [comment]
![image](https://user-images.githubusercontent.com/49649786/164231728-780e8365-5b19-4a60-a260-25f275f7c464.png)
通过文档名首尾字符渲染颜色, 最后一个是
`.文档名`
