### ISSUE TITLE
:bug: 在新窗口打开当前块一直加载

### ISSUE THREAD

**Issue by Achuan-2** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#174]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

思源笔记 2.7.0 dev2 ， 使用Dark+的【 在新窗口打开当前块】会提示“Need remove unused code”，并且一直加载，无法编辑文档

### 期待的结果 Expected result

能够正常打开新窗口并编辑文档

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/60436214/212620916-eb65e44a-d495-4a7b-8899-bbccfb0dfebc.png)

![image](https://user-images.githubusercontent.com/60436214/212620926-31b9481c-929f-4119-b404-3a582193343b.png)

### 版本环境 Version environment

```markdown
- SiYuan Version: v2.7.0 dev2
- Dark+ Version: v1.6.4
- Operating System: Win11
- Browser (if used):
```

### 更多信息 More information

无

**Comment by Zuoqiu-Yingyi** [comment]
下个版本兼容 [Pull Request #7086 · siyuan-note/siyuan](https://github.com/siyuan-note/siyuan/pull/7086) 后再瞅瞅

**Comment by Zuoqiu-Yingyi** [comment]
`v2.7.0+` 版本直接使用了思源的实现应该解决了(〃'▽'〃)

**Comment by Achuan-2** [comment]
是的，感谢
