### ISSUE TITLE
列表表格视图分割线取最长列表项块

### ISSUE THREAD

**Issue by mdzz2048** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#175]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

如图：感觉有点突兀
![image](https://user-images.githubusercontent.com/86549958/212807175-8f0097cb-51f1-424b-9231-6d02deb69107.png)

```
* limit：

  * 200
* latest_updated_at：

  *
* latest_slug：

  * ""
* tz：

  * 8:0
* timestamp：

  *
* api_key：

  * flomo_web
* app_version：

  * 2.0
* webp：

  * 1
* sign：

  *
```

### 描述可能的最优解决方案 Describe the optimal solution

![image](https://user-images.githubusercontent.com/86549958/212807985-a616671a-6dcf-4bb6-b5c1-3054955f5ae0.png)

**Comment by Zuoqiu-Yingyi** [comment]
按照目前的实现方案这不太好实现😂

**Comment by mdzz2048** [comment]
好嘞，那我先用表格顶顶
