### ISSUE TITLE
新年快乐

### ISSUE THREAD

**Issue by AugustTuan** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#176]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

![9C7E2A1D1776BEF2DBAF74B7C5CEBDFB](https://user-images.githubusercontent.com/37429029/213911114-d829f137-9f84-4d64-8696-f63f83995ecf.gif)

### 描述可能的最优解决方案 Describe the optimal solution

![S~WC3@KS)%H~N)ZM`0U%QMO](https://user-images.githubusercontent.com/37429029/213911086-b91fcc72-c276-451a-ab05-251cc0a3206b.gif)

### 描述候选的解决方案 Describe the candidate solution

![V)4@~X%XFCV%(1$0`XH`0](https://user-images.githubusercontent.com/37429029/213911093-c2278501-f42b-4a29-bf57-70b0b7fd89f3.gif)

### 其他信息 Other information

![9090~DAZ$U9Z5CK 625(QKC](https://user-images.githubusercontent.com/37429029/213911101-897874eb-4218-4a0c-b537-1606280ccf3b.jpg)

**Comment by AugustTuan** [comment]
萌新妹子，新年快乐，感谢制作这么优秀的主题☆*: .｡. o(≧▽≦)o .｡.:*☆

**Comment by Zuoqiu-Yingyi** [comment]
原来还能这么拜年呀, 同乐同乐 ღ( ´･ᴗ･` )
