### ISSUE TITLE
标签支持设置颜色

### ISSUE THREAD

**Issue by AugustTuan** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#177]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

贴标签的时候，希望给不同地标签设置颜色。
标签本身的特色，就是能用不同的颜色起到象征意义。
现在的所有标签都一个颜色，多个标签排在一起就失去焦点了

### 描述可能的最优解决方案 Describe the optimal solution

![image](https://user-images.githubusercontent.com/37429029/216798211-68d78df6-fe21-460d-a3ba-3f6081d5f9b4.png)
![image](https://user-images.githubusercontent.com/37429029/216801332-561999d9-e9d0-4681-87e7-80e5d2a17e6c.png)

**Comment by Zuoqiu-Yingyi** [comment]
划选标签文本后使用弹出菜单中的 <kbd>字体</kbd> 功能即可
![image](https://user-images.githubusercontent.com/49649786/216816465-6793d149-5531-42a1-8eb2-fdeb752c55fc.png)

**Comment by AugustTuan** [comment]
> 划选标签文本后使用弹出菜单中的 字体 功能即可 ![image](https://user-images.githubusercontent.com/49649786/216816465-6793d149-5531-42a1-8eb2-fdeb752c55fc.png)

用字体颜色区别的话
同一个标签，每次添加，都需要手动改一次字体吗？

**Comment by Zuoqiu-Yingyi** [comment]
> 用字体颜色区别的话 同一个标签，每次添加，都需要手动改一次字体吗？

可以使用模板功能
