### ISSUE TITLE
:bug: 打开新窗口、 Monaco 编辑器窗口似乎不能用了？

### ISSUE THREAD

**Issue by winter60** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#178]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

使用Dark+主题，似乎使用鼠标中键、alt+中键、alt+shift+中键等用不了了
![image](https://user-images.githubusercontent.com/23653326/217561404-00ea221a-28c6-419d-afa7-8060085462a6.png)

### 期待的结果 Expected result

能用。

### 版本环境 Version environment

```markdown
- SiYuan Version: 2.7.3
- Dark+ Version: 1.7.0
- Operating System: win
- Browser (if used):
```

**Comment by Zuoqiu-Yingyi** [comment]
使用 <kbd>Ctrl + F5</kbd> 重新加载界面后试试, 可能主题 `theme.js` 在切换时命中了缓存

**Comment by winter60** [comment]
已解决，不能在Dark+主题下重复引用自身的`theme.js`
