### ISSUE TITLE
:bug: Dark+ v1.7.0的自定义样式失效

### ISSUE THREAD

**Issue by sq98** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#179]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

升级到Dark+ v1.7.0后，自定义样式失效了，经测试之前自定义的custom-light.css失效了，(估计custom-dark.css应该也失效了，此未测)。

### 期待的结果 Expected result

希望在此 或 在项目README.md里，更新适用于Dark+ v1.7.0的自定义样式的方法，谢谢！谢谢开发出这么好用，这么棒的主题👍🏻！（看到 项目的README.md是两个月前的更新，应该还没来得及更新）

### 版本环境 Version environment

```markdown
- SiYuan Version: 2.7.4
- Dark+ Version: 1.7.0
- Operating System: MacOS 12.6.1
- Browser (if used):
```

**Comment by sq98** [comment]
谢谢，已看到了你的修复。但是当我按照你修复后的代码，同样的操作之后（也就是删除 theme.js 里那两行关键的代码后），重启再打开思源笔记，依然未加载未显示自定义样式。（不知是不是还没修复完成）。

需要注意的是，项目的 README.md里 自定义配置里的 <工作空间>/conf/appearance/themes/Dark+/style/**color**/light.css，在1.7.0版本中已经删除，路径变为了 <工作空间>/conf/appearance/themes/Dark+/style/**config**/light.css。

原本 custom-light.css 覆盖的是 /**color**/light.css 中的值，现在没有了/**color**/light.css，只有/**config**/light.css，不知是否和这有关。

**Comment by sq98** [comment]
谢谢，已看到了你的修复。但是当我按照你修复后的代码，同样的操作之后（也就是删除 theme.js 里那两行关键的代码后），重启再打开思源笔记，依然未加载未显示自定义样式。（不知是不是还没修复完成）。

需要注意的是，项目的 README.md里 自定义配置里的 <工作空间>/conf/appearance/themes/Dark+/style/**color**/light.css，在1.7.0版本中已经删除，路径变为了 <工作空间>/conf/appearance/themes/Dark+/style/**config**/light.css。

原本 custom-light.css 覆盖的是 /**color**/light.css 中的值，现在没有了/**color**/light.css，只有/**config**/light.css，不知是否和这有关。

**Comment by Zuoqiu-Yingyi** [comment]
> 谢谢，已看到了你的修复。但是当我按照你修复后的代码，同样的操作之后（也就是删除 theme.js 里那两行关键的代码后），重启再打开思源笔记，依然未加载未显示自定义样式。（不知是不是还没修复完成）。
> 
> 需要注意的是，项目的 README.md里 自定义配置里的 <工作空间>/conf/appearance/themes/Dark+/style/**color**/light.css，在1.7.0版本中已经删除，路径变为了 <工作空间>/conf/appearance/themes/Dark+/style/**config**/light.css。
> 
> 原本 custom-light.css 覆盖的是 /**color**/light.css 中的值，现在没有了/**color**/light.css，只有/**config**/light.css，不知是否和这有关。

其实我并没有成功复现该问题, 只是删除了两句冗余的代码, 要不先试试禁用缓存后刷新界面😂

**Comment by sq98** [comment]
作者已在项目主页里的README.md里，更新了自定义样式的代码举例，请参考修改。

其实也就是：
1.把data/widgets/custom.css里的 :root { 改为如下两行即可
:root[data-theme-mode=light],
:root[data-theme-mode=dark] {

2.把data/widgets/custom-light.css里的 :root { 改为如下一行即可
:root[data-theme-mode=light] {

3.把data/widgets/custom-dark.css里的 :root { 改为如下一行即可
:root[data-theme-mode=dark] {

其它不用改，上面三处改完后，关闭思源笔记后重新打开即可。我刚改过，完美显示自定义样式。

**Comment by sq98** [comment]
作者已在项目主页里的README.md里，更新了自定义样式的代码举例，请参考修改。

其实也就是：
1.把data/widgets/custom.css里的 `:root {` 改为如下两行即可
```
:root[data-theme-mode=light],
:root[data-theme-mode=dark] {
```

2.把data/widgets/custom-light.css里的 `:root` { 改为如下一行即可
`:root[data-theme-mode=light] {`

3.把data/widgets/custom-dark.css里的 `:root` { 改为如下一行即可
`:root[data-theme-mode=dark] {`

其它不用改，上面三处改完后，关闭思源笔记后重新打开即可。我刚改过，完美显示自定义样式。

**Comment by Geo123abc** [comment]
> 作者已在项目主页里的README.md里，更新了自定义样式的代码举例，请参考修改。 @Geo123abc 其实也就是：
> 
> 1.把data/widgets/custom.css里的 :root { 改为如下两行即可
> 
> ```
> :root[data-theme-mode=light],
> :root[data-theme-mode=dark] {
> ```
> 
> 2.把data/widgets/custom-light.css里的 :root { 改为如下一行即可 `:root[data-theme-mode=light] {`
> 
> 3.把data/widgets/custom-dark.css里的 :root { 改为如下一行即可 `:root[data-theme-mode=dark] {`
> 
> 其它不用改，上面三处改完后，关闭思源笔记后重新打开即可。我刚改过，完美显示自定义样式。

谢谢老铁
