### ISSUE TITLE
请教一下，为什么有的列表支持转表格，有的不支持

### ISSUE THREAD

**Issue by AugustTuan** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#184]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

如图，有的无序列表点击以后有更多这个选项
![image](https://user-images.githubusercontent.com/37429029/221359422-025196c7-039a-4b4b-aa65-708221e67368.png)
有的就没有
![image](https://user-images.githubusercontent.com/37429029/221359497-8cee9719-9426-4698-b040-b3a75fa74759.png)

**Comment by Zuoqiu-Yingyi** [comment]
这是一个 :bug:, 详情请参考 #183, 下个版本修复

**Comment by AugustTuan** [comment]
好嘞，谢谢
