### ISSUE TITLE
更新以后，任务列表勾选后，所有的子项都会被打上删除线

### ISSUE THREAD

**Issue by Yuminis98** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#186]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

之前不是这个样子的。

最近一段时间更新以后，任务列表勾选，所有的子列表项都会打上删除线

我这里有300多道面试题，原来记录的。 都是以列表项的形式存在。
现在想正常浏览列表项里面呢内容，只有先手动取消勾选了

### 期待的结果 Expected result

只有列表项所在的文本加删除线，
列表项内部的文本不加删除线。

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/117956441/223335964-1443b127-a2ef-45c3-be2b-b4f5154c7656.png)

### 版本环境 Version environment

```markdown
- SiYuan Version: 2.7.7
- Dark+ Version: 最新
- Operating System: win
- Browser (if used):
```

**Comment by Zuoqiu-Yingyi** [comment]
请关注 [改进任务列表项完成后的样式 by Zuoqiu-Yingyi · Pull Request #7599 · siyuan-note/siyuan](https://github.com/siyuan-note/siyuan/pull/7599)
