### ISSUE TITLE
使用“查看Markdown源代码”功能批量编辑后，内容丢失:bug: 

### ISSUE THREAD

**Issue by tcmtom** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#189]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

一整个内容块，使用“查看Markdown源代码”功能批量编辑后，只剩下了第一个内容块

### 期待的结果 Expected result

不丢失内容

### 截屏或者录屏演示 Screenshot or screen recording presentation

[2023-03-28-22-42-40.zip](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/files/11090760/2023-03-28-22-42-40.zip)

### 版本环境 Version environment

```markdown
- SiYuan Version: 2.8.0
- Dark+ Version: 1.7.4
- Operating System: win10
- Browser (if used):
```

### 更多信息 More information

思源每一个块都有一个唯一的ID，新生成的段落块没有ID显示，可能是这个问题导致的。

**Comment by Zuoqiu-Yingyi** [comment]
这是思源 API [更新块](<https://github.com/siyuan-note/siyuan/blob/master/API_zh_CN.md#%E6%9B%B4%E6%96%B0%E5%9D%97>) 的限制, 没有比较好的解决方法

**Comment by Zuoqiu-Yingyi** [comment]
> 和D大去提会不会有解决办法？

可以尝试反馈一下？

**Comment by Zuoqiu-Yingyi** [comment]
> 我不会组织语言，萌佬试试？我的录屏什么的可以拿去用

我感觉现在就挺好的, 毕竟是稳定的 API

可以通过编辑容器块实现多块编辑👀

**Comment by Zuoqiu-Yingyi** [comment]
超级块 / 引述块 / 列表项 / 文档块 都可以同时编辑多个块, 不过需要使用 kramdown 编辑模式
