### ISSUE TITLE
:sparkles: 希望ctrl+0是恢复字体默认大小

### ISSUE THREAD

**Issue by luo-chuan** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#190]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

插件市场“编辑器字体缩放”过来的，试了下ctrl+0快捷键，并没有这个功能，希望能支持。

### 描述可能的最优解决方案 Describe the optimal solution

这样该快捷键就能和浏览器保持一致了。

**Comment by Zuoqiu-Yingyi** [comment]
参考 vscode & github.dev, DOM 缩放与编辑区缩放是两个完全不同的操作, 因此优化方向反而应该是在浏览器中禁用 <kbd>Ctrl/⌘ + 鼠标滚轮</kbd> DOM 缩放

**Comment by Zuoqiu-Yingyi** [comment]
[Support mouse wheel zoom editor font size · Issue #8064 · siyuan-note/siyuan](https://github.com/siyuan-note/siyuan/issues/8064)

下个版本思源原生实现了鼠标滚轮缩放, 我先关闭了\~
