### ISSUE TITLE
:sparkles: 集市主题图标

### ISSUE THREAD

**Issue by StarDustSheep** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#192]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

替换之前的图标

### 描述可能的最优解决方案 Describe the optimal solution

![icon](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/assets/114859111/aa049222-8b60-47ae-833e-78669c302431)

**Comment by Zuoqiu-Yingyi** [comment]
@all-contributors please add @StarDustSheep for design

**Comment by Zuoqiu-Yingyi** [comment]
@all-contributors please add @StarDustSheep for design

**Comment by Zuoqiu-Yingyi** [comment]
@all-contributors please add @StarDustSheep for design
