### ISSUE TITLE
:bug: 图片显示模糊

### ISSUE THREAD

**Issue by shenjinglei** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#194]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

使用Dark+主题后，png图片显示略有模糊，如下图。上方是思源+Dark+主题渲染的结果，下方是原图
![Snipaste_2023-05-18_09-16-28](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/assets/11613616/d661cce9-e8e4-494a-8934-59461dd9f3ca)
下图是思源的原始主题的对比图，上方是思源+原始主题渲染的结果，下方是原图
![Snipaste_2023-05-18_09-17-10](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/assets/11613616/c749ddb2-cf9a-4dfc-bf95-a2db23d5e166)
暂时只测试了PNG图片

### 期待的结果 Expected result

希望使用Dark+主题后，图片显示不再模糊。

### 版本环境 Version environment

```markdown
- SiYuan Version: v2.8.8
- Dark+ Version: v1.9.0
- Operating System: win10
- Browser (if used):
```

**Comment by Zuoqiu-Yingyi** [comment]
我这里的图片好像与默认主题没啥区别, 能将示例图片附上我测试一下吗?

**Comment by shenjinglei** [comment]
![Snipaste_2023-05-18_09-17-24](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/assets/11613616/aeb6def8-b59d-460c-99ce-1c436e3b1cbc)

**Comment by shenjinglei** [comment]
我用开发者工具看了下，图片本来大小是291*78，现在显示只有281*75.31，所以会显示模糊。
![Snipaste_2023-05-18_17-08-32](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/assets/11613616/12dd5188-b44a-4a82-9541-a784487f48dc)
然后把img上的display: inline-block; 取消掉就能显示图片的完整大小了
![Snipaste_2023-05-18_17-09-33](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/assets/11613616/e8c54533-b1f8-4bab-848d-a943e0a9967a)
![Snipaste_2023-05-18_17-12-18](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/assets/11613616/34c8bb86-361d-4dda-a558-31b8efd8a66e)
所以，我把span-img.css中的相应css注释掉就恢复正常了
![image](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/assets/11613616/a46e0d6e-4a01-4363-90f8-c02f55c40e31)
我对前端不熟，所以，我的方法不是最好的，希望能提供一些提示。
