### ISSUE TITLE
:bug: 右上角的工具栏无法关闭和移动

### ISSUE THREAD

**Issue by brian763** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#196]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

![image](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/assets/16741077/3e543af0-c5e9-400d-9799-74b4b7d24f70)
请问工具栏在哪里关闭？我想把他拖到不想要的位置，于是发现拖到右上角里面，这下好了，既无法移动也不知道哪里关闭了

### 期待的结果 Expected result

![image](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/assets/16741077/32871f22-66d1-48c1-a851-50aa743f17a1)
请问工具栏在哪里关闭？我想把他拖到不想要的位置，于是发现拖到右上角里面，这下好了，既无法移动也不知道哪里关闭了

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/assets/16741077/75e6867c-c5ec-4505-8c8b-e8f6090d73e6)

### 版本环境 Version environment

```markdown
- SiYuan Version: 最新
- Dark+ Version: 最新
- Operating System: Win10
- Browser (if used):无
```

**Comment by brian763** [comment]
请问一下，在哪个css的哪个位置可以把这个浮动的工具栏关闭呢？

**Comment by Zuoqiu-Yingyi** [comment]
点击窗口最小化左边那个按钮可以重置悬浮工具栏的状态
