### ISSUE TITLE
升级后Crtl+滚轮对页面进行缩放不起作用

### ISSUE THREAD

**Issue by minghengzhang** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#197]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

升级前可以用Crtl+滚轮对页面进行缩放，这也是我选择drak主题的主要原因，之前也出现过该问题，回退版本就OK了，这次不知道是思源主版本的问题还是主题的原因，回退也不起作用了。现在只能用整体窗口缩放代替了

### 期待的结果 Expected result

功能恢复到以前就行，真是很好用。

### 版本环境 Version environment

```markdown
- SiYuan Version: 2.9.3
- Dark+ Version: 1.9.5
- Operating System: win10
- Browser (if used):
```

**Comment by Zuoqiu-Yingyi** [comment]
现在思源本体内置了该功能, 可以在 `设置` > `编辑器` > `快速调整字号` 中打开

**Comment by minghengzhang** [comment]
已解决

> 现在思源本体内置了该功能, 可以在 `设置` > `编辑器` > `快速调整字号` 中打开
