### ISSUE TITLE
:bug: 

### ISSUE THREAD

**Issue by fatbOy6666** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#200]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

笔记本写的内容同步到台式机以后，视频和图片的颜色全部失真，关闭主题以后恢复正常

### 期待的结果 Expected result

能否帮忙查看下具体是哪段代码导致？

### 截屏或者录屏演示 Screenshot or screen recording presentation

笔记同步以后，关掉主题，正常情况
![image](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/assets/48044812/83f5e5fc-241a-42ce-b4b9-b4177bc4d2c1)
![image](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/assets/48044812/0acb59bf-a364-48e0-9e96-125d42aa2270)
![image](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/assets/48044812/93b6911c-4102-468f-b066-e779f0fd75c5)
笔记同步以后，打开主题，异常情况
![image](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/assets/48044812/77026a6d-9a92-4865-99e7-5875752c1a59)
![image](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/assets/48044812/bdea7638-5887-4820-85a5-b84e5dfd7066)
![image](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/assets/48044812/be76a1e1-3b16-49ca-ab7e-6eb333db35bf)

### 版本环境 Version environment

```markdown
- SiYuan Version: V2.9.4
- Dark+ Version:V1.9.6 
- Operating System: Win10 教育版
- Browser (if used): 没有浏览器
```

**Comment by Zuoqiu-Yingyi** [comment]
检查一下主题的悬浮工具栏中的 `反色显示` 功能是否开启了

**Comment by fatbOy6666** [comment]
感谢回复，但是悬浮栏工具都没有了，我重装了笔记工具还有主题好多次也不行
![image](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/assets/48044812/86e8da14-1b31-47c1-852d-e45a60a54204)
我确认了我的确应用了这个主题
![image](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/assets/48044812/3b316d14-04a7-48dc-9909-33dba49f4088)

**Comment by fatbOy6666** [comment]
没事了，多谢回复，重建工作目录搞定了，再次感谢
