### ISSUE TITLE
:bug: 文档以 点号 开头，在文档树中，显示为空

### ISSUE THREAD

**Issue by zhoutaosheng** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#204]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

如下，.class 文档，在文档树中，显示为空
![image](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/assets/5683995/23c507a9-d63e-4f2b-9134-b5ce821b09e5)

已经确定，默认主题没有问题

### 期待的结果 Expected result

表现正确

### 版本环境 Version environment

```markdown
- SiYuan Version: 2.10.0
- Dark+ Version: 1.10.0
- Operating System: Windows 11
- Browser (if used):
```

### 更多信息 More information

无

**Comment by zhoutaosheng** [comment]
使用默认主题，表现正确
![image](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/assets/5683995/cb828621-eaf1-4752-87e8-b301df76b0fd)

**Comment by Zuoqiu-Yingyi** [comment]
这是一个特性, 用于在文档树中隐藏指定的文档名

**Comment by zhoutaosheng** [comment]
> 这是一个特性, 用于在文档树中隐藏指定的文档名

@Zuoqiu-Yingyi 问下，在哪关闭这个特性

**Comment by Zuoqiu-Yingyi** [comment]
> 问下，在哪关闭这个特性，比如在代码中，哪里关闭这个特性

在 设置 > 外观 > 自定义代码片段 > CSS 片段 中添加如下片段即可
```css
:root {
    --custom-doctree-begin-period-color: var(--b3-theme-on-background);
}
```
