### ISSUE TITLE
使用dark+后图片都是处于反色状态:bug: 

### ISSUE THREAD

**Issue by jhzerone** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#209]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

不知道为什么我的思源笔记, 使用dark+图片会显示反色的状态,
比如下面这张截图:
![image](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/assets/58368113/a428b9af-4abe-4ae6-9da5-041d6178ff83)
思源里面:
![image](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/assets/58368113/c9340c4b-141e-40da-bf7f-f518b311749e)

### 期待的结果 Expected result

正常显示图片颜色

### 版本环境 Version environment

```markdown
- SiYuan Version:  v2.10.10
- Dark+ Version: v1.10.2
- Operating System: win10
- Browser (if used):
```

**Comment by Zuoqiu-Yingyi** [comment]
请检查是否开启了 `反色显示` 功能

**Comment by jhzerone** [comment]
原来确实有个反色显示的按钮选中了.. 感谢..
