### ISSUE TITLE
:bug: 代码块行号不对齐

### ISSUE THREAD

**Issue by DearLi111** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#210]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

代码块行号不对齐

### 期待的结果 Expected result

行号可以对齐

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/assets/35019122/8a2e8654-be5a-427e-bb75-7e4324636e6a)

### 版本环境 Version environment

```markdown
- SiYuan Version: v2.10.14
- Dark+ Version: v1.10.3
- Operating System: docker
- Browser (if used): chrome
```

**Comment by Zuoqiu-Yingyi** [comment]
我这里未能复现该问题
请检查一下 `代码块美化` (`siyuan-plugin-code-block`) 插件
