### ISSUE TITLE
:bug: 闪卡问题页标记内容不会被覆盖

### ISSUE THREAD

**Issue by etchnight** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#213]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

间隔重复-闪卡，问题页标记内容不会被覆盖，即会显示答案

### 期待的结果 Expected result

根据闪卡设计，问题页标记文本的文字颜色应该是透明色，但是因为如下主题css规则，无法实现预期效果

.card__block:not(.card__block--hidemark) .protyle-wysiwyg [data-node-id] mark:not([style]), .card__block:not(.card__block--hidemark) .protyle-wysiwyg [data-node-id] span[data-type~=mark]:not([style]), .card__block.card__block--hidemark .protyle-wysiwyg [data-node-id] mark:hover:not([style]), .card__block.card__block--hidemark .protyle-wysiwyg [data-node-id] span[data-type~=mark]:hover:not([style]) {
    color: var(--custom-span-mark-color) !important;
}

即，以下css规则不起作用

.card__block.card__block--hidemark .protyle-wysiwyg [data-node-id] mark, .card__block.card__block--hidemark .protyle-wysiwyg [data-node-id] span[data-type~=mark], .protyle-wysiwyg [data-node-id] mark:not(:hover), .protyle-wysiwyg [data-node-id] span[data-type~=mark]:not(:hover) {
    color: transparent;
}

考虑更改为以下规则（在自定义css中测试有效）
.card__block.card__block--hidemark .protyle-wysiwyg div[data-node-id] mark,
.card__block.card__block--hidemark
  .protyle-wysiwyg
  div[data-node-id]
  span[data-type~="mark"],
.protyle-wysiwyg [data-node-id] mark:not(:hover),
.protyle-wysiwyg [data-node-id] span[data-type~="mark"]:not(:hover) {
  color: transparent !important;
}

### 截屏或者录屏演示 Screenshot or screen recording presentation

修改前：
![捕获](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/assets/39119983/942b9024-383b-4b4a-952d-4ba6b4438eae)
修改后：
![捕获2](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/assets/39119983/bca0b3b8-8036-40f1-9644-f8d4edfcb371)

### 版本环境 Version environment

```markdown
- SiYuan Version: v2.11.4
- Dark+ Version: v1.10.4
- Operating System: win10
- Browser (if used):
```

**Comment by Zuoqiu-Yingyi** [comment]
在最新版本思源 `v2.12.2` 中闪卡页面中标记文本会显示为 `[...]`, 如下图所示
![image](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/assets/49649786/da2033f1-9196-4c2c-a0c2-efa45a07edf1)

**Comment by etchnight** [comment]
嗯嗯，新版本确实不存在这个问题了
