### ISSUE TITLE
:bug:列表辅助线开关无用 

### ISSUE THREAD

**Issue by Simuliya** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#214]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

如题,关闭列表辅助线还是有,还是说我对列表辅助线的理解有歧义?重启也还是有辅助线

### 期待的结果 Expected result

可以关闭辅助线

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/assets/127732514/05e2fbed-beb8-489a-b4f1-1af4946e54d1)

### 版本环境 Version environment

```markdown
- SiYuan Version: 最新
- Dark+ Version: 最新
- Operating System: 
- Browser (if used):
```

**Comment by minghengzhang** [comment]
我的需求和题主相反，以前版本中有子弹线，现在的列表辅助线开关点击没有效果

**Comment by Zuoqiu-Yingyi** [comment]
定位到问题了, 这是因为之前我将 `列表辅助线` 功能所依赖的 `获取当前编辑焦点` 的功能迁移到了插件 `[打字机模式 `typewriter`](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-typewriter) 中但是忘了更新文档😂

解决方案: 安装插件 `打字机模式` (`typewriter`) 并开启该插件的 `焦点设置` > `显示当前焦点` 功能
