### ISSUE TITLE
如让之前已经标亮的部分不展示挖空效果

### ISSUE THREAD

**Issue by aptexd** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#22]
开发者你好
因为之前已经用高亮标注了很多重点，改用该主题后，直接显示挖空，无法流畅阅读
这个功能很好，但由于路径依赖我已经没有办法改变用法
所以试问下能否将“遮盖”或“挖空”这个功能加上开关
打开就是挖空，关闭就是原来的类似高亮的功能

**Comment by Zuoqiu-Yingyi** [comment]
[feat: 添加自定义块属性 mark: 显示 与一项块菜单项以显示标记文本](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/commit/63a55aa3071700d7a6536ed9634511da26e9bac6)
下个版本能通过块属性 `mark: display` 或者 `mark: 显示` 控制, 并将快捷操作添加到了块菜单
