### ISSUE TITLE
弹幕会产生滚动条

### ISSUE THREAD

**Issue by WolkeAtreide** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#23]
请看下图，在dark+的时候，下方会产生一个动态的滚动条，大概是为了配比长度的。但是使用张亮的弹幕的时候这个滚动条是没有的。不知道dark+的弹幕能否将此物去除掉呢？
dark+
![image](https://user-images.githubusercontent.com/101959415/164357932-8a0e79cb-9a73-4fcf-8b9c-96925ce26224.png)
zhang liang
![image](https://user-images.githubusercontent.com/101959415/164357977-e3f80cbb-2a32-4eae-9fc0-20383c6d4af6.png)

**Comment by Zuoqiu-Yingyi** [comment]
@WolkeAtreide 这是特性, 只要光标焦点不在弹幕块中, 这个滚动条就不会出现

**Comment by WolkeAtreide** [comment]
> @WolkeAtreide 这是特性, zhang-light 没有设置整个块为弹幕, 我将整个块设置为弹幕了

明白，我可以两段代码都保留，看需求使用。
