### ISSUE TITLE
能否增加一个保持菜单位置的特性？

### ISSUE THREAD

**Issue by WolkeAtreide** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#24]
如图，开启块菜单增强后，菜单太长，会直接被覆盖掉一部分，能不能让他自动调整位置，从而能显示全部呢？
只是一点建议
![image](https://user-images.githubusercontent.com/101959415/164361811-f18cf68c-8cc5-4a42-83b7-cdb49e84ce2f.png)

**Comment by Zuoqiu-Yingyi** [comment]
[fix: 修复块菜单面板超出可视窗口问题](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/commit/72cd9e73c7ef206bdb68670b0dfdf1c580928e99)

**Comment by WolkeAtreide** [comment]
> [fix: 修复块菜单面板超出可视窗口问题](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/commit/72cd9e73c7ef206bdb68670b0dfdf1c580928e99)
貌似没有修复成功？
![image](https://user-images.githubusercontent.com/101959415/164891965-d0ac0cee-9b7c-408b-89ab-7c229dbdf1ad.png)

**Comment by Zuoqiu-Yingyi** [comment]
> 

禁用缓存后强制刷新试试

**Comment by Zuoqiu-Yingyi** [comment]
@WolkeAtreide 禁用缓存后强制刷新试试
