### ISSUE TITLE
块菜单增强按钮非常好用，能否设置为默认开启？

### ISSUE THREAD

**Issue by WolkeAtreide** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#25]
没找到相关功能
![image](https://user-images.githubusercontent.com/101959415/164417382-63090d44-c631-4d72-bdaf-870468ea6399.png)

**Comment by Zuoqiu-Yingyi** [comment]
Dark+ `v0.8.2+` 版本会保存这些开关状态, 并在下次加载完成后自动还原

**Comment by WolkeAtreide** [comment]
> Dark+ `v0.8.2+` 版本会保存这些开关状态, 并在下次加载完成后自动还原

详细了解一下，0.8.2的意思是，这个特性已经有了么？我尝试了一下。ctrlF5也好，重启软件也好，都不能储存开关状态，

**Comment by Zuoqiu-Yingyi** [comment]
> > Dark+ `v0.8.2+` 版本会保存这些开关状态, 并在下次加载完成后自动还原
> 
> 详细了解一下，0.8.2的意思是，这个特性已经有了么？我尝试了一下。ctrlF5也好，重启软件也好，都不能储存开关状态， 我的js文件如下，应该没啥关系吧~~大概： ![image](https://user-images.githubusercontent.com/101959415/164892190-2a1b20a9-6f3f-4ca5-a4e6-4ffa3f2cda73.png)

请检查一下 widgets 目录下有没有 `custom.json` 文件, 注意, 不是 `custom.js` 文件

**Comment by WolkeAtreide** [comment]
> > > Dark+ `v0.8.2+` 版本会保存这些开关状态, 并在下次加载完成后自动还原
> > 
> > 
> > 详细了解一下，0.8.2的意思是，这个特性已经有了么？我尝试了一下。ctrlF5也好，重启软件也好，都不能储存开关状态， 我的js文件如下，应该没啥关系吧~~大概： ![image](https://user-images.githubusercontent.com/101959415/164892190-2a1b20a9-6f3f-4ca5-a4e6-4ffa3f2cda73.png)
> 
> 请检查一下 widgets 目录下有没有 `custom.json` 文件, 注意, 不是 `custom.js` 文件

没有这个文件，需要自己建一个不？

**Comment by Zuoqiu-Yingyi** [comment]
可能和 #24 是同一个原因造成的

**Comment by WolkeAtreide** [comment]
> 说明配置没有写入, 可能和 #24 是同一个原因造成的

所以是bug喽？我不用管喽？
完美~

**Comment by Zuoqiu-Yingyi** [comment]
> > 说明配置没有写入, 可能和 #24 是同一个原因造成的
> 
> 所以是bug喽？我不用管喽？ 完美~

可能不是bug, 是浏览器缓存机制的问题, 浏览器没有加载新版本的文件

**Comment by Zuoqiu-Yingyi** [comment]
请查看帮助文档 siyuan://blocks/20201225202158-gfmyvql

**Comment by WolkeAtreide** [comment]
> 说明配置没有写入, 可能和 #24 是同一个原因造成的

刷新以后确实两个都能用了。我不李姐，我都删除重装了，我不李姐。
谢了~谢了~问题解决！
