### ISSUE TITLE
关于列表块下拉菜单

### ISSUE THREAD

**Issue by WolkeAtreide** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#26]
我记得之前用的时候，列表块有下拉菜单。现在用没了，是去掉此功能了么？

**Comment by Zuoqiu-Yingyi** [comment]
我这里还在呀

**Comment by WolkeAtreide** [comment]
> 我这里还在呀
我大概嘴瓢了，想说代码块来。
奇怪，我把自定义全部去掉也不管用，应该不是自定义的锅
![image](https://user-images.githubusercontent.com/101959415/164884717-045cffed-e121-418f-9dbb-f2a903b05a78.png)
![image](https://user-images.githubusercontent.com/101959415/164884720-0b274584-2668-41ee-853d-54eb8f0d603d.png)

**Comment by Zuoqiu-Yingyi** [comment]
@WolkeAtreide 我的代码块也在呀😂

**Comment by WolkeAtreide** [comment]
> @WolkeAtreide 我的代码块也在呀😂
属实离谱了。。

**Comment by WolkeAtreide** [comment]
> @WolkeAtreide 我的代码块也在呀😂

知道了，以前是默认显示的，现在需要增加属性render:scroll

**Comment by Zuoqiu-Yingyi** [comment]
> > @WolkeAtreide 我的代码块也在呀😂
> 
> 知道了，以前是默认显示的，现在需要增加属性render:scroll

以前也不是默认显示的, 可能是自定义的样式片段, 然后升级后被覆盖了, 嘿嘿~

**Comment by WolkeAtreide** [comment]
> > > @WolkeAtreide 我的代码块也在呀😂
> > 
> > 
> > 知道了，以前是默认显示的，现在需要增加属性render:scroll
> 
> 以前也不是默认显示的, 可能是自定义的样式片段, 然后升级后被覆盖了, 嘿嘿~

别说，有了增强菜单以后，这样才是最好用的。
