### ISSUE TITLE
建议：脑图视图下，重写tab键和shift+tab键的作用

### ISSUE THREAD

**Issue by winter60** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#27]
萌佬你好~建议监听这个按键，重写tab键的作用，只是建议，不好实现可以忽略

现在的情况 ：
按tab键的会将当前块变成哥哥的儿子
按shift+tab键会将当前块变成父亲的弟弟

期待的情况：
按tab键会从当前块生一个儿子
按shift+tab键不起任何作用。

**Comment by Zuoqiu-Yingyi** [comment]
确实不好实现, 因为这需要修改DOM树, V姐好不容易将列表的bug改的差不多了, 我可不敢再塞入更多的bug了😂

**Comment by winter60** [comment]
> 确实不好实现, 因为这需要修改DOM树, V姐好不容易将列表的bug改的差不多了, 我可不敢再塞入更多的bug了😂

好的，感谢回复~
