### ISSUE TITLE
如何全局关闭遮盖效果

### ISSUE THREAD

**Issue by aptexd** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#31]
开发者你好
很喜欢这款主题，前期用原生主题做了很多高亮笔记，现在显示是遮盖的效果
虽然出出了 `mark:display` 模式，但还是不很方便，因为太多了
那现在有方法可以全局屏蔽这个遮盖效果吗

**Comment by Zuoqiu-Yingyi** [comment]
注释 `conf\appearance\themes\Dark+\theme.css` 文件中的

```css
@import url(/appearance/themes/Dark+/style/module/span-mark.css);
```
这一行即可
