### ISSUE TITLE
列表的脑图视图与表格视图中列表项内如何恢复纵向排版

### ISSUE THREAD

**Issue by Elliootalderson** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#32]
首先, 列表视图转脑图视图真的太惊艳了, 我实在忍不住夸赞,让我记笔记也更加有动力了.看着自己做的思维导图,感觉非常满足!

但是有兩点我需要说一下
第一,本来是一个块结构中的文字和代码块,换成导图后就变成了代码块成为了文字的子节点,非常影响排版(造成排版变得很长)和导图上的逻辑错误.如下图:
列表模式: 
![image](https://user-images.githubusercontent.com/93273663/166714242-1ba8cfd6-6209-479e-9f5b-f7dab3d25566.png)
导图模式:
![image](https://user-images.githubusercontent.com/93273663/166714589-7ccdc488-670c-4e90-91ca-20dc9304efde.png)

第二.当代码块太长时.显示bug
![image](https://user-images.githubusercontent.com/93273663/166714834-eced31d8-18b4-4ba7-891e-d67d13805ef3.png)

**Comment by WorkSync** [comment]
@Zuoqiu-Yingyi 老师，请问一下。列表转导图的功能，主题已经不内置了，需要单独下载插件custom-block是吗？我在主题的块菜单里面找了一下，没有看到转导图的选项。
另外求问，块菜单中，如何让插件功能选项，直接出现在块菜单里面，而不是折叠在“插件”这一项里🙏

**Comment by Zuoqiu-Yingyi** [comment]
> 列表转导图的功能，主题已经不内置了，需要单独下载插件custom-block是吗？

是的

> 块菜单中，如何让插件功能选项，直接出现在块菜单里面，而不是折叠在“插件”这一项里

这个目前不好实现，插件 API 添加的菜单项都在 `插件` 这一项中
