### ISSUE TITLE
专注模式

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#34]
> 我有个功能需求，你看有没有兴趣？
> 类似专注模式 Alt+Y，但仅仅是左上、左下、右上、右下的侧边栏收起，恢复时弹出上一次记忆的侧边栏。
> 需求原因：有分屏需要，但官方专注模式仅为单页面。
> 如果能实现的话，真是十分感谢！❤️

**Comment by Geo123abc** [comment]
这个功能像现在搞了吗？急需

**Comment by Zuoqiu-Yingyi** [comment]
> 这个功能像现在搞了吗？急需

可能一周后才能腾出时间开发😭

**Comment by Geo123abc** [comment]
嗯嗯呢，辛苦了，我自己手动先顶顶

**Comment by Geo123abc** [comment]
专注模式收否可以把 “隐藏停靠栏”顺便也一起实现了？

**Comment by Zuoqiu-Yingyi** [comment]
> 专注模式收否可以把 “隐藏停靠栏”顺便也一起实现了？

隐藏停靠栏是思源自带的功能呀

**Comment by Geo123abc** [comment]
> > 专注模式收否可以把 “隐藏停靠栏”顺便也一起实现了？
> 
> 隐藏停靠栏是思源自带的功能呀

确实是自带的，但是专注模式的目的之一，不就是提高屏幕的利用率吗？如果专注模式能把隐藏停靠栏一起带上，岂不是更好？

**Comment by Zuoqiu-Yingyi** [comment]
> 确实是自带的，但是专注模式的目的之一，不就是提高屏幕的利用率吗？如果专注模式能把隐藏停靠栏一起带上，岂不是更好？

那我为该功能添加一个默认关闭的选项吧, 如果有需要, 可以通过 `custom.js` 将其打开

**Comment by Geo123abc** [comment]
期待

**Comment by Zuoqiu-Yingyi** [comment]
@Geo123abc 将 `config.theme.dock.fold.dock` 设置为 `true` 时打开该选项

**Comment by Geo123abc** [comment]
是在 custom-light.css  文件中直接添加 	`config.theme.dock.fold.dock = true;`  吗？

**Comment by Zuoqiu-Yingyi** [comment]
> 是在 custom-light.css 文件中直接添加 `config.theme.dock.fold.dock = true;` 吗？

需要在 `custom.js` 中设置

**Comment by Geo123abc** [comment]
> > 不知道该怎么改
> 
> 可以参考一下自述文档的这个 [custom.js](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus#customjs)
> 
> ```js
> export const config = {
>     theme: {
>         dock: {
>             fold: {
>                 dock: true,
>             },
>         },
>     },
> };
> ```

三个问题：
1. <工作空间>/data/widgets/custom.js  还是 <工作空间>/data/widgets/custom.json
2. <工作空间>/data/widgets/custom.json  这个文件每次都会被思源还原
3. 如果开启专注模式，然后退出思源笔记，再重启思源笔记的时候，仍然是专注模式，但是dark+的按钮就不起作用了，只能手动点击文件树、大纲树，两者显示之后，专注模式才能起作用，这是否是个bug？

**Comment by Zuoqiu-Yingyi** [comment]
> 三个问题：
> 
> 1. <工作空间>/data/widgets/custom.js  还是 <工作空间>/data/widgets/custom.json
> 2. <工作空间>/data/widgets/custom.json  这个文件每次都会被思源还原
> 3. 如果开启专注模式，然后退出思源笔记，再重启思源笔记的时候，仍然是专注模式，但是dark+的按钮就不起作用了，只能手动点击文件树、大纲树，两者显示之后，专注模式才能起作用，这是否是个bug？

1. `<工作空间>/data/widgets/custom.js` 是用户自定义配置文件, `<工作空间>/data/widgets/custom.json` 是用户状态文件, 保存用户当前使用状态
2. 该文件在主题部分功能开关状态发生变化时被覆盖
3. 这是因为思源本身也有保存面板折叠/展开状态的功能, 我试试能不能改进一下

**Comment by Geo123abc** [comment]
> > 不知道该怎么改
> 
> 可以参考一下自述文档的这个 [custom.js](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus#customjs)
> 
> ```js
> export const config = {
>     theme: {
>         dock: {
>             fold: {
>                 dock: true,
>             },
>         },
>     },
> };
> ```

抄作业，没抄成功，我蠢哭了

![](https://s3.bmp.ovh/imgs/2022/06/13/01f07a5e98b2d988.png)
