### ISSUE TITLE
弹幕的控制按钮固定在原始位置不随弹幕移动

### ISSUE THREAD

**Issue by lentikr** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#36]
![show](https://user-images.githubusercontent.com/95539012/167235191-cb5a2b46-8bf8-4055-9311-618ea28ca3b4.gif)

**Comment by Zuoqiu-Yingyi** [comment]
这个特性是为了适配所有的块, 应该不影响吧😂

**Comment by lentikr** [comment]
> 这个特性是为了适配所有的块, 应该不影响吧😂

在弹幕左端超过笔记编辑页面时这个控制按钮也会出现在笔记编辑页面外，总感觉还是有点怪呢，而且也不好操作

**Comment by Zuoqiu-Yingyi** [comment]
> > 这个特性是为了适配所有的块, 应该不影响吧😂
> 
> 在弹幕左端超过笔记编辑页面时这个控制按钮也会出现在笔记编辑页面外，总感觉还是有点怪呢，而且也不好操作

我不打算改了, 不过如果需要的话可以给你发个自定义片段~
