### ISSUE TITLE
能否增加复制 当前文档所有子文档为 有序列表、无序列表、任务列表的功能？

### ISSUE THREAD

**Issue by Geo123abc** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#38]
现在有复制当前文档大纲为 有序列表、无序列表、任务列表的功能，能否增加复制 当前文档所有子文档为 有序列表、无序列表、任务列表的功能。
这里有一个quicker动作可以 [自动生成思源文档目录 - 动作信息 - Quicker](  https://getquicker.net/Sharedaction?code=bb5ee874-93b3-406d-0373-08da2d65ae66  )

**Comment by Zuoqiu-Yingyi** [comment]
这个功能可以使用模板实现呀, 比如集市中 Normal 模板中的目录, 还可以自己调整层级

**Comment by Zuoqiu-Yingyi** [comment]
现在可以使用集市中的 [OpaqueGlass/listChildDocs: 用于创建更新子文档目录列表的思源笔记挂件。](https://github.com/OpaqueGlass/listChildDocs) 挂件实现了~
