### ISSUE TITLE
关于钉住

### ISSUE THREAD

**Issue by WolkeAtreide** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#39]
更新后发现钉住的标签长度似乎调整了，能否告知原代码是多少？我针对原长度是由一套quicker动作的，改短了就不太好实现了

**Comment by Zuoqiu-Yingyi** [comment]
啊?

**Comment by WolkeAtreide** [comment]
这里的长度dark+和其他主题不一样，是加长的，现在也改为缩短了。
![image](https://user-images.githubusercontent.com/101959415/167733006-347ef150-5252-4cff-9b04-55af6d6046ca.png)

**Comment by WolkeAtreide** [comment]
这是原来的长度
![image](https://user-images.githubusercontent.com/101959415/167734904-fadc3bdf-da58-4ea8-94e5-668c5a92ee7b.png)

**Comment by WolkeAtreide** [comment]
好吧，奇怪的是2.0.7版本又变回来了。看来是软件问题，不是主题问题。
