### ISSUE TITLE
有序列表序号偏低导致导出PDF有误

### ISSUE THREAD

**Issue by litcu** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#40]
如下图所示，序号4应该是在“基因”前面的，但导出PDF时若序号刚好位于换页的前一行，就会出现BUG。

![6a8ce9f73f4c7608e6a3119d3f40792](https://user-images.githubusercontent.com/53759402/167861555-946c75a3-8b7c-4e36-b387-04b8205846b7.png)

**Comment by Zuoqiu-Yingyi** [comment]
由于为了方便在其他主题引用样式, 这个主题是不支持 PDF 与 HTML 导出的👀

**Comment by Zuoqiu-Yingyi** [comment]
这个优化应该解决了该问题: [Improve PDF export paging strategy by Zuoqiu-Yingyi · Pull Request #8110 · siyuan-note/siyuan](https://github.com/siyuan-note/siyuan/pull/8110)
