### ISSUE TITLE
标题和段落也支持导图视图

### ISSUE THREAD

**Issue by Elliootalderson** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#41]
目前好像只有有序列表和无序列表在同一个列表项中才能显示出导图选项,希望可以扩展到标题和段落, 不在同一个列表项中的列表可以

**Comment by Zuoqiu-Yingyi** [comment]
由于标题块和段落块是同级的, 不是列表块与列表项那种包含与被包含的结构, 所以无法实现所述功能😂
