### ISSUE TITLE
建议顶部工具栏增加“显示/隐藏标记文本”和“页面透明度”的设置

### ISSUE THREAD

**Issue by o-ut-man** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#42]
“标记文本”一般用来做着重标记的，所以默认隐藏违背了初衷， 现在只能针对块设置，希望能增加快捷的全局设置
“页面透明度”主要是部分背景图片在当前透明度下，容易导致内容辨识度降低，希望增加快捷设置

**Comment by Zuoqiu-Yingyi** [comment]
标记文本可以通过设置文档块属性的方式显示整篇文档, 不过如果有需要的话, 我下个版本可以添加一个全局显示/隐藏标记的功能

**Comment by Zuoqiu-Yingyi** [comment]
页面透明度可以参考一下 #33, 修改一下想要设置的颜色
主编辑区的背景颜色的变量为 `--custom-editor-background-color`

**Comment by Zuoqiu-Yingyi** [comment]
[feat: 使用快捷键 `Shift + Alt + E` 启用/关闭显示标记文本功能](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/commit/d9fba7aca4d89b811ef06cdf6cff3e1d4c3ecdb3)
