### ISSUE TITLE
建议：增加空行的占位符的隐藏设置

### ISSUE THREAD

**Issue by o-ut-man** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#44]
空行有时候会用于排版间隔，现在的默认占位符太突出了
<img width="279" alt="Snipaste_2022-05-12_16-36-17" src="https://user-images.githubusercontent.com/34265164/168028854-8b78cdd1-1ffd-42e4-91e9-74c184b2e1a8.png">

**Comment by Zuoqiu-Yingyi** [comment]
REF: #37
