### ISSUE TITLE
电脑分屏后，页签显示问题

### ISSUE THREAD

**Issue by UltramarineSky** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#46]
思源升级到2.0.8后，如果电脑分屏，标签页打开较多，前面的页签可能有部分显示不出来

![2 0 8 分屏页签显示问题](https://user-images.githubusercontent.com/54146035/168192228-093fabdf-1a7b-4247-bac6-e7af34c904cc.gif)

**Comment by Zuoqiu-Yingyi** [comment]
[fix: 修复页签项阴影遮挡上一行页签项问题 @40c1211](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/commit/40c1211f5b4ec3e83672231ccf3fdb4815a213de)
