### ISSUE TITLE
标题折叠展开功能无效

### ISSUE THREAD

**Issue by clark874** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#49]
思源笔记2.08版本后的Dark+中出现标题折叠展开点击小三角无效，望作者修复。

谢谢！

**Comment by Zuoqiu-Yingyi** [comment]
这个是思源的 bug [块标纵向排列以后折叠小三角失效](https://github.com/siyuan-note/siyuan/issues/4876), 应该在思源下个版本中会修复
