### ISSUE TITLE
搜索窗口大小与关闭按钮的位置

### ISSUE THREAD

**Issue by Geo123abc** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#50]
现在搜索窗口比较大，确实很好，便于在搜索到的条目右侧编辑。
但是也有一个问题，搜索界面的关闭按钮和思源主程序的关闭按钮太近了，容易误点，不知道有没有其他人也遇到过这样的困惑？是否考虑调整一下？

**Comment by Zuoqiu-Yingyi** [comment]
可以通过单击窗口以外的区域/使用 <kbd>Esc</kbd> 按键都可以关闭窗口

**Comment by Geo123abc** [comment]
> 

OK，谢谢，在搜索界面，再一次按搜索快捷键，也可以关闭，不过esc更方便
