### ISSUE TITLE
新建页面的小bug？

### ISSUE THREAD

**Issue by jipeng0918** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#51]
![image](https://user-images.githubusercontent.com/43375185/168475208-881dfe85-bf86-4a39-b0de-d5b605d1f8e5.png)
在页面中新建页面，然后跳转到新页面，输入标题后，原页面的内容没有跟着改变。默认主题正常。

不知道说清楚没，就是我在这个日历表格里新建某一天的页面，自动跳到新页面标题输入比如15，原来页面日历中没有跟着改变

**Comment by Zuoqiu-Yingyi** [comment]
块引用分为动态锚文本与静态锚文本两种, 动态锚文本才会在被引用的内容更改时自动更改

**Comment by jipeng0918** [comment]
> 

不知道。同样的操作，在默认主题是正常的。

**Comment by Zuoqiu-Yingyi** [comment]
是不是这个问题: [重命名文档动态锚文本未跟随](https://github.com/siyuan-note/siyuan/issues/4893)
