### ISSUE TITLE
关于记录浏览位置

### ISSUE THREAD

**Issue by WolkeAtreide** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#52]
目前发现，他只会在屏幕右上角记录下当前浏览位置的块id，并不能自动跳转。
有什么方法能自动跳转么？光知道块id似乎也没什么用处。

**Comment by WolkeAtreide** [comment]
私以为这个功能可以用来记录关闭软件前最后浏览位置，若是能自动跳转，就解决了每次都要翻页的痛点

**Comment by Zuoqiu-Yingyi** [comment]
右键单击块滚动条就能跳转上次浏览位置呀

**Comment by WolkeAtreide** [comment]
哎呦，不错哦~

**Comment by WolkeAtreide** [comment]
1. 记录浏览位置的功能设计初衷是为了解决什么问题？
2. 这个东西在关闭功能后去不掉
![image](https://user-images.githubusercontent.com/101959415/168518789-0f15bbdb-7c03-496d-ad1d-c376d2c2f625.png)

**Comment by WolkeAtreide** [comment]
另外，我试验了一下，右键单击非常不准确、、
点不动，这个功能是思源本体带的么？

**Comment by WolkeAtreide** [comment]
会用了
