### ISSUE TITLE
功能块隐藏

### ISSUE THREAD

**Issue by SamJ2018** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#53]
[
![image](https://user-images.githubusercontent.com/37620490/168705992-a14150fe-b850-4c83-b7f0-029b01135e80.png)
](url)

功能块在调整大小的时候会变得很小甚至被隐藏。能不能加一个类似>>的按钮，自适应大小，放不下的扔到>>中

**Comment by Zuoqiu-Yingyi** [comment]
不太好实现, 目前 `v0.9.10` 里面有个 <kbd>更多</kbd> 按钮可以折叠, 要不先用这个顶顶😂

**Comment by SamJ2018** [comment]
> 

好的，感谢回复

**Comment by Zuoqiu-Yingyi** [comment]
在 `v1.1.1` 版本中将 <kbd>更多</kbd> 按钮替换为了 <kbd>折叠/展开</kbd> 按钮, 应该更方便一些
