### ISSUE TITLE
列表-表格视图失效

### ISSUE THREAD

**Issue by clark874** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#54]
可能是因为版本升级的缘故，列表转换表格功能失效，只能转换为如下效果：
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/86122040/168724247-d0292d5e-1549-4e80-a0a9-ffd52106a19a.png">
尝试了其它主题中的类似功能，也全部失效了。
希望作者能够修复，感谢！

**Comment by Zuoqiu-Yingyi** [comment]
能发一下 markdown 源码嘛, 我这里没有失效👀
