### ISSUE TITLE
支持特殊字符自动标记颜色

### ISSUE THREAD

**Issue by Geo123abc** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#56]
目前使用思源笔记写论文，做笔记，使用zotero管理文献，文献引用的格式是：[@zhang1999]，[@li2022; @zhao2022] ，是否可以把这些字符自动识别出来并显示为特殊颜色（比如蓝色）？

[zotero 联合 markdown 软件-以思源笔记为例 - 知乎](  https://zhuanlan.zhihu.com/p/463073230  )

**Comment by Zuoqiu-Yingyi** [comment]
感觉手动标记应该更好一些吧👀

**Comment by Geo123abc** [comment]
> 感觉手动标记应该更好一些吧👀

我觉得自动识别更好一些，可以专心于写作，符合markdown的宗旨

**Comment by Zuoqiu-Yingyi** [comment]
> 我觉得自动识别更好一些，可以专心于写作，符合markdown的宗旨

可以使用超链接, 我一般使用 `[@yao2021](zotero://select/library/items/4P36MZNV "[A Survey on Causal Inference]")` 这种方案, 在保留锚文本的同时还可以悬浮显示超链接的 `title` 中的内容(我这里设置为了文章标题 `[A Survey on Causal Inference]`), 同时可以单击该超链接跳转到 zotero 对应的项中(我这里是 `zotero://select/library/items/4P36MZNV`)
