### ISSUE TITLE
能否将主题默认背景改为纯色

### ISSUE THREAD

**Issue by woaihuangxueying** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#58]
现在这个默认的主题背景实在是太花太丑了，基本上平常交流过这个主题的人都得自己去改背景。

能否将主题背景默认为纯色，
自己想要添加背景的，再往文件添加图片。

而不是现在这样，默认一样很花的背景图，让用户自己去更换成纯色。 有点本末倒置

这样也可以避免新用户上来被颜值给劝退，而没有机会领略到Dark+的诸多功能。

如有冒犯，还请海涵。

**Comment by Zuoqiu-Yingyi** [comment]
但是纯色更丑😂

**Comment by Geo123abc** [comment]
咱俩想到一起了，分享一下我的自定义

D:\SiYuan\data\widgets\custom-light.css



:root {
    /* 子标题及其对应大纲颜色 ，使用dark+主题中 D:\SiYuan\conf\appearance\themes\Dark+\style\module\config.css  自定义标准颜色(Office 标准颜色) ，由于黄色在主题中显示度太差，因此改为黑色*/
    --custom-h1-color: #FA0000;
    --custom-h2-color: #FFC001;
    --custom-h3-color: #000000;
    --custom-h4-color: #00B050;
    --custom-h5-color: #00B0F0;
    --custom-h6-color: #7030A0;
    
    /* 空行聚焦提示 */
    --custom-empty-focus-p: "";
    --custom-empty-focus-c: "´･-･)ﾉ↹";
    --custom-empty-focus-t: "´･-･)ﾉ☑";
    --custom-empty-focus-u: "´･-･)ﾉ◉";
    --custom-empty-focus-o: "´･-･)ﾉ①";
    
    /* 空行提示 */
    --custom-empty-p: "";
    --custom-empty-c: "";
    --custom-empty-t: "";
    --custom-empty-u: "";
    --custom-empty-o: "";


    /* 默认背景图片 */
    --custom-background-image: url("/appearance/themes/background (07).png");
}


图片是把dark+的一张图裁剪之后，调整分辨率得到的，全灰

![](https://s3.bmp.ovh/imgs/2022/05/24/51a21a89450d9564.png)

**Comment by woaihuangxueying** [comment]
> 但是纯色更丑😂

或者我这个帖子的诉求可以改一下，

就是能否抽出一点精力提高一下 Dark+默认的颜值😂

我推荐给身边认识人、网友，一共5个使用思源的人下载DARK+主题，

 基本下载了都说，好难看。

 我说功能很多啊，如果想更改，可以自定义blablabla

然后人家就说，就是想用个主题而已，这么麻烦啊，还是算了。

我就无话可说了😔，颜值是第一生产力😂。

**Comment by Zuoqiu-Yingyi** [comment]
@woaihuangxueying @Geo123abc 下个版本添加一个背景颜色 css 变量吧, 在自定义配置样式文件中设置如下即可

```css
:root {
    /* 背景图片 | Background image */
    --custom-background-image: none;
    /* 背景颜色 | Background color */
    --custom-background-color: <想要的颜色>;
}
```

**Comment by Geo123abc** [comment]
> @woaihuangxueying @Geo123abc 下个版本添加一个背景颜色 css 变量吧, 在自定义配置样式文件中设置如下即可
> 
> ```css
> :root {
>     /* 背景图片 | Background image */
>     --custom-background-image: none;
>     /* 背景颜色 | Background color */
>     --custom-background-color: <想要的颜色>;
> }
> ```

1. --custom-background-image: url("/appearance/themes/background (07).png");
2.     /* 背景图片 | Background image */
    --custom-background-image: none;
    /* 背景颜色 | Background color */
    --custom-background-color: <想要的颜色>;

从技术上讲，方案1和方案2，哪一个消耗资源比较少，加载快？

**Comment by Zuoqiu-Yingyi** [comment]
> 从技术上讲，方案1和方案2，哪一个消耗资源比较少，加载快？

方案二

**Comment by Geo123abc** [comment]
> > 从技术上讲，方案1和方案2，哪一个消耗资源比较少，加载快？
> 
> 方案二

谢谢，那我去改一下

**Comment by Geo123abc** [comment]
@Zuoqiu-Yingyi  ，没实现啊，最后那个颜色值没有起作用

    /* 默认背景图片 */
    /* --custom-background-image: url("/appearance/themes/background (07).png");*/

    --custom-background-image: none;
    /* 背景颜色 | Background color */
    --custom-background-color: #C7EDCC;

**Comment by Zuoqiu-Yingyi** [comment]
> @Zuoqiu-Yingyi ，没实现啊，最后那个颜色值没有起作用

集市还没更新, 可以先从仓库下载

**Comment by Geo123abc** [comment]
> > @Zuoqiu-Yingyi ，没实现啊，最后那个颜色值没有起作用
> 
> 集市还没更新, 可以先从仓库下载

噢噢噢，明白了。
![0fbbd745ef2b7823130b7d854d92048b](https://user-images.githubusercontent.com/76165569/170824498-99991a64-b2f5-4af5-808b-88960d1f16aa.png)
