### ISSUE TITLE
空行样式可以改一下吗？现在和正文几乎没法区分

### ISSUE THREAD

**Issue by HoGafi** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#59]
![image](https://user-images.githubusercontent.com/32252229/170155592-377aec9d-c398-49e8-a9dc-270e9f31eaa8.png)
如图

**Comment by Zuoqiu-Yingyi** [comment]
请参考 [https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus#customcss](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus#customcss)
