### ISSUE TITLE
编辑区表情选择框被横向切割了？

### ISSUE THREAD

**Issue by git-zxx** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#60]
这个情况是主题设定还是只有我是这样的😶，我要怎样改回去原来的样子呢 :D
![image](https://user-images.githubusercontent.com/42286494/170630464-f7b669fd-5528-43ac-8407-318a8ffa66be.png)
我确实按照主题说明自定义了外观，但是我把那些`custom.x`文件移出去重新安装了主题还是会这样，自己实在找不到解决办法了，过来求助555

**Comment by Zuoqiu-Yingyi** [comment]
应该不是主题的问题吧, 我这里是正常的~
![image](https://user-images.githubusercontent.com/49649786/170630917-fd4f5d82-793c-422f-879f-a4d75c02caff.png)

**Comment by Zuoqiu-Yingyi** [comment]
> 你这个是正斜杠唤出的菜单里面的吗，我文档题上面那个表情列表正常，但是下面的`/`唤出菜单中的表情列表就不正常了 ![image](https://user-images.githubusercontent.com/42286494/170650815-b779c354-2277-49bf-bed6-c2a96281a952.png) ![image](https://user-images.githubusercontent.com/42286494/170650970-93494826-6a62-43ef-9098-a1bca8c88a9f.png)

感谢(･ω･)ﾉ, 已经定位到问题了, 下个版本修复 [fix: 修复编辑区的 emojis 选择菜单样式问题](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/commit/9de5a502ab405bd1fa2674744f5fe45f7f879a53)

**Comment by git-zxx** [comment]
感动哭了ಥ_ಥ

**Comment by Zuoqiu-Yingyi** [comment]
@git-zxx 貌似这个问题又出现了, 下个版本再修复一次~
