### ISSUE TITLE
文档中有两个一级标题会导致复制文档大纲失败（Dark+未改动可复现）

### ISSUE THREAD

**Issue by git-zxx** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#61]
刚刚像复制大纲发现怎么也复制不到，然后自己测试了一下原因：
* 当文档中有两个一级标题的时候，就会出现这种问题
* 而我却什么也没复制到，我测试了几次发现：复制大纲并不会复制一级标题，只会复制≥2级的标题，而且文档中有两个一级标题的时候，只会复制第二个一级标题下的子标题。
* 我那个文档中有批注，批注功能会自动创建一个一级标题，然后批注内容全是非标题块，这样复制的时候，就什么也复制不到
复现方法：文档中包含两个标题，第一个标题是文档的标题，第二个一级标题让批注功能生成即可，这样复制文档大纲就会失败（如图）
![image](https://user-images.githubusercontent.com/42286494/170695951-b16adff6-512c-48e9-b8a2-50213b66eb78.png)

**Comment by Zuoqiu-Yingyi** [comment]
这是因为思源 API 发生了更改, Dark+ 下个版本修复: [build: 复制大纲功能适配 v2.0.13 的 API 与 DOM](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/commit/27b955197bbca6b3907c85cf5c9a21dd458eb80c)
