### ISSUE TITLE
替换页面出现的bug

### ISSUE THREAD

**Issue by lentikr** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#63]
在滴链上看到的，自己尝试了下，发现默认主题没有这个问题，应该是Dark+的问题。
[替换输入框被隐藏](https://ld246.com/article/1653871398175)

**Comment by Zuoqiu-Yingyi** [comment]
收到

**Comment by lentikr** [comment]
在1.0.5中似乎没有被修复
