### ISSUE TITLE
小问题

### ISSUE THREAD

**Issue by Tukali** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#65]
1./命令展示的效果可以一次全部展示出来吗，现在变成了一个竖排，好多常用的不方便使用
<img width="351" alt="CleanShot 2022-05-31 at 16 33 20@2x" src="https://user-images.githubusercontent.com/45891208/171129675-88578e1d-0c3e-4336-9989-8a9e340c655d.png">

2.挂件菜单里面可以去掉custom.json和custom.css嘛，这个实际场景不会使用还是产生干扰
![CleanShot 2022-05-31 at 16 13 54@2x](https://user-images.githubusercontent.com/45891208/171129972-89042cc8-453d-44ac-8bd8-f0ccf72c7c9b.png)

**Comment by Zuoqiu-Yingyi** [comment]
感谢反馈, 已修复

**Comment by Tukali** [comment]
> 

好的，谢谢师傅
