### ISSUE TITLE
自动编号数字错乱

### ISSUE THREAD

**Issue by CoRiver** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#69]
不知道前面的编号规律是什么，好像也不是从头开始标号的
![uTools_1655211450929](https://user-images.githubusercontent.com/24204805/173582976-b71ed3be-e2fb-4703-99f5-dff835fb7ccb.png)
![uTools_1655211506414](https://user-images.githubusercontent.com/24204805/173582986-b346db12-d9fc-46ff-a53c-cd1a5f94949f.png)

**Comment by Zuoqiu-Yingyi** [comment]
这是由于标题自动编号使用 CSS 计数器实现, 因此在触发思源动态加载时(不从文档首开始加载时)会导致编号错误, 该问题无法解决, 抱歉

**Comment by CoRiver** [comment]
原来如此，好吧=_=
