### ISSUE TITLE
docker部署下手机浏览器的文档树界面完全透明

### ISSUE THREAD

**Issue by moon4869** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#70]
具体效果如下，几乎看不清文档树内容了，想问下这个透明度有自定义样式的地方吗？
![3c27c3dd2dd57e03296d68c8afdf072](https://user-images.githubusercontent.com/33173163/173747940-af9200d0-cd6e-483b-afaa-93020a5d818a.jpg)

**Comment by Zuoqiu-Yingyi** [comment]
我这里并未出现这种情况👀
请使用浏览器访问, 看是否依然出现该情况

![image](https://user-images.githubusercontent.com/49649786/173891864-d8e01b67-5b9d-4fa4-9b2b-f5dc330ba6fa.png)

**Comment by moon4869** [comment]
浏览器的问题，换个浏览器就好了。。。
但是还是想问下这个样式可以自己修改吗？

**Comment by Zuoqiu-Yingyi** [comment]
> 这个样式可以自己修改吗？

可以, 在自定义 CSS 配置文件中设置即可

```css
#sidebar {
    background-color: <想要使用的颜色>;
}
```

**Comment by moon4869** [comment]
> 可以, 在自定义 CSS 配置文件中设置即可
> 
> ```css
> #sidebar {
>     background-color: <想要使用的颜色>;
> }
> ```

感谢，已完美解决需求
