### ISSUE TITLE
如何把关系图背景改成不透明的？

### ISSUE THREAD

**Issue by blessor** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#72]
默认好像是透明的，在哪里改成不透明的呀

**Comment by Zuoqiu-Yingyi** [comment]
`v1.1.3` 版本可以使用 CSS 变量 `--custom-panel-graph-fullscreen-background-color` 定义了🎉

**Comment by blessor** [comment]
> `v1.1.3` 版本可以使用 CSS 变量 `--custom-panel-graph-fullscreen-background-color` 定义了🎉

大佬神速呀。
感觉自定义配置加个default选项，就是和无主题的一样，会很方便。

**Comment by Zuoqiu-Yingyi** [comment]
> 感觉自定义配置加个default选项，就是和无主题的一样，会很方便。

可以在其他主题的 `theme.css` 文件首部引用 `Dark+` 的部分样式文件, 在默认主题中也可以

**Comment by blessor** [comment]
> > 感觉自定义配置加个default选项，就是和无主题的一样，会很方便。
> 
> 可以在其他主题的 `theme.css` 文件首部引用 `Dark+` 的部分样式文件, 在默认主题中也可以

确实。

**Comment by blessor** [comment]
> `v1.1.3` 版本可以使用 CSS 变量 `--custom-panel-graph-fullscreen-background-color` 定义了🎉

我这里局部关系图背景重定义了。
但全局关系图背景还是透明。

**Comment by Zuoqiu-Yingyi** [comment]
> 我这里局部关系图背景重定义了。 但全局关系图背景还是透明。

感谢, 现已修复~
