### ISSUE TITLE
关闭就旧窗口，新窗口也关闭。

### ISSUE THREAD

**Issue by blessor** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#73]
有窗口1，
打开窗口2，
关闭窗口1，则2也关闭。
但关闭2,1不关闭。

**Comment by Zuoqiu-Yingyi** [comment]
@blessor 我这里没有出现这个问题呀👀

**Comment by blessor** [comment]
> @blessor 我这里没有出现这个问题呀👀
![111](https://user-images.githubusercontent.com/12458188/174545434-434a498b-bdec-41f7-ab82-5198e0f4b271.jpg)

我们说的是一个窗口吧。
就是用“打开一个新窗口”按钮打开窗口。
如果把原窗口关闭，则新窗口也关闭。

**Comment by blessor** [comment]
😂
