### ISSUE TITLE
“关闭按钮设置”问题

### ISSUE THREAD

**Issue by woniuxia** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#74]
设置“关闭按钮设置”，会影响到外观模式的切换，详情见录屏。

https://user-images.githubusercontent.com/16383685/174576769-553b329c-8e19-4fac-9bff-7b21a372f4b0.mp4

**Comment by Zuoqiu-Yingyi** [comment]
> 设置“关闭按钮设置”，会影响到外观模式的切换，详情见录屏。

我这里在切换这个开关状态时没有出现样式切换的问题❓~

**Comment by woniuxia** [comment]
很神奇。。。
我又试了下，notion 也没有这个问题。
辛苦再看下。

https://user-images.githubusercontent.com/16383685/174692477-3159b440-f9d6-4ac9-938c-81bf5d25c49b.mp4


https://user-images.githubusercontent.com/16383685/174692465-8a1fd4db-794b-458c-86ff-bee57a5445e7.mp4

**Comment by woniuxia** [comment]
卸载其他主题也会导致这个问题
Uploading 20220621_083046.mp4…
