### ISSUE TITLE
请问如何给一级标题二级标题换颜色呢

### ISSUE THREAD

**Issue by qing-root** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#75]
![image](https://user-images.githubusercontent.com/30001685/176991510-0178d4a6-63db-41ee-adfe-a8073f86252a.png)
请问下如果给一级二级标题换颜色呢，找了一圈css没找到相关设置的文件呀，可以给个文件提示吗

**Comment by Zuoqiu-Yingyi** [comment]
在 `config.css` 文件中定义的颜色, 可以使用 `widgets/custom.css`, `widgets/custom-light.css` 与 `widgets/custom-dark.css` 覆盖
https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/blob/e3c8dc2ece0296de6dc0352ca552adf9e562bf33/style/module/config.css#L155-L161

**Comment by qing-root** [comment]
感谢
