### ISSUE TITLE
【文档树、设置】字体变小

### ISSUE THREAD

**Issue by yxy823** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#76]
使用 ctrl + 滚轮缩放编辑区的字体的时候，突然文档树字体变小，之后打开设置发现字体也变小了。
![image](https://user-images.githubusercontent.com/38773494/176996283-15626870-c1f1-42f3-9b31-5a7e983ba3e5.png)

**Comment by Zuoqiu-Yingyi** [comment]
请检查是否是误触了 <kbd>Ctrl + =</kbd> 或 <kbd>Ctrl + -</kbd>
这会调整整个窗口的字体大小, 可以使用 <kbd>Ctrl + 0</kbd> 或设置>外观>恢复默认窗口重置
