### ISSUE TITLE
内存占用率很高

### ISSUE THREAD

**Issue by lentikr** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#8]
不知道为什么，使用官方主题时内存占用能控制在300MB以内，但使用本主题时内存占用一直在1500MB左右
![image](https://user-images.githubusercontent.com/95539012/163569052-857cf2ad-21bc-48ac-8356-bb074a0f11c7.png)

**Comment by lentikr** [comment]
发现了触发的条件：从应用菜单打开日记，内存占用会迅速增长

**Comment by Zuoqiu-Yingyi** [comment]
请继续跟踪该问题
