### ISSUE TITLE
标题前的自动序号错误

### ISSUE THREAD

**Issue by Himitsu98** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#80]
当我通过大纲点击，转到一个非第一个一级标题A时，此一级标题前的自动生成的序号就会变成1，其后的二级标题序号全会变为1.x，其后的一级标题B序号为2，而实际上这个A的实际序号应为13，B的实际序号为14。请问这是个bug还是特性？
比如，当我从文档首页开始，向下浏览至相应位置时，序号正常：
![屏幕截图 2022-07-06 223420](https://user-images.githubusercontent.com/40586792/177575844-552295e8-6547-4057-8750-633cd04d47f6.png)
而当我从大纲点击至此标题后，显示异常：
![屏幕截图 2022-07-06 223440](https://user-images.githubusercontent.com/40586792/177575960-27014c12-a2e8-4d58-b248-ff7a94d32603.png)

**Comment by Zuoqiu-Yingyi** [comment]
请参考 #69
