### ISSUE TITLE
特性请求：能否为block增加font-size属性

### ISSUE THREAD

**Issue by jabobian** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#82]
有时候复制到思源中的文本采用了Tab等格式化，如果用代码块，只能看到局部，如果用换行，格式就乱了，希望使用小号的字体。
目前采用 html 格式，但是不够方便。

**Comment by Zuoqiu-Yingyi** [comment]
> 有时候复制到思源中的文本采用了Tab等格式化，如果用代码块，只能看到局部，如果用换行，格式就乱了，希望使用小号的字体。
> 目前采用 html 格式，但是不够方便。

使用css设置的话需要穷举字号，不太优雅

要不试试在 `/widgets/custom.css` 文件中自定义一个块属性样式

**Comment by Zuoqiu-Yingyi** [comment]
现在可以在 `块扩展菜单`>`更多`>`块样式` 菜单项中使用 CSS 语句直接设置该块的样式了
