### ISSUE TITLE
打开PDF标注时，指针移到标注上时会不停闪烁，难以选中。

### ISSUE THREAD

**Issue by Wsssk** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#83]
![录制_2022_07_13_16_17_45_9](https://user-images.githubusercontent.com/97886221/178685606-b594c2f7-0429-4c3d-8e56-a3f9779388dd.gif)
切换到默认主题就解决了。希望作者能修复一下想继续使用这个主题！十分感谢！

**Comment by Zuoqiu-Yingyi** [comment]
请参考 #81, 该问题已经修复, 不过集市版本还未合并更新
