### ISSUE TITLE
编辑区的内边距怎么调大一点

### ISSUE THREAD

**Issue by git-zxx** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#87]
如下面视频的情况（之前没有发生），编辑区好像太宽了，总是需要拖动才能看到右端，加载结束滚动条依然存在。怎样让编辑区窄一点呢，不需要左右拖动就能显示完整。或者，是我自定义的哪些内容导致了这个问题吗，我怎么改过来呢（自定义文件好久没动过了，之前显示是正常的，最近两次更新后就这样了）

https://user-images.githubusercontent.com/42286494/179352122-e276d51a-ae51-453d-ad30-f93571378037.mp4

**Comment by git-zxx** [comment]
额，大佬，解决了，思源开启自适应宽度就好了。

**Comment by Zuoqiu-Yingyi** [comment]
请参考 #84
