### ISSUE TITLE
公式块的背景颜色和边框颜色能否自定义

### ISSUE THREAD

**Issue by jabobian** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#88]
插入公式块，会有灰色的背景和中灰色的边框，
和Html块的配置似乎是一样的，能否区别对待，
看起来有点别扭，公式背景颜色还是默认的透明或浅浅色比较美观，
如果在属性中设置更佳。

Thanks!

**Comment by jabobian** [comment]
好奇怪，我什么也没做，现在公式块和文本块一样颜色了，也是我想要的效果。

**Comment by Zuoqiu-Yingyi** [comment]
> 插入公式块，会有灰色的背景和中灰色的边框，
> 和Html块的配置似乎是一样的，能否区别对待，
> 看起来有点别扭，公式背景颜色还是默认的透明或浅浅色比较美观，
> 如果在属性中设置更佳。
> 
> Thanks!

这是之前的bug，可能之前的文件缓存没失效
