### ISSUE TITLE
请问如何更换字体呢

### ISSUE THREAD

**Issue by chaseleaf** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#9]
需要替换默认的字体，但是没找到相应的css文件，和其他主题的赊账方法好像不一样，无法通过直接把字体放到文件夹 加字体命令实现。

**Comment by Zuoqiu-Yingyi** [comment]
默认配置文件为 `conf\appearance\themes\Dark+\style\module\config.css` 可以使用文件(若没有则新建) `data\widgets\custom.css` 覆盖默认配置文件的项
