### ISSUE TITLE
Monaco Editor无法保存公式块

### ISSUE THREAD

**Issue by 1995hanjian** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#93]
![image](https://user-images.githubusercontent.com/39188734/182279276-63a16592-753f-4576-bbc8-37d5a54f9054.png)
如图所示，当用Monaco Editor编辑公式块后，并没有办法保存~

**Comment by Zuoqiu-Yingyi** [comment]
能稳定复现吗

**Comment by 1995hanjian** [comment]
> 能稳定复现吗

至少我这里是很稳定地都不能编辑公式块TAT
