### ISSUE TITLE
折叠标题会现一个“口”

### ISSUE THREAD

**Issue by HerrHuang** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#95]
折叠标题会现一个“口”
<img width="487" alt="image" src="https://user-images.githubusercontent.com/64797182/183134710-c926a4eb-4146-46ec-9b54-63d64acf1b65.png">
<img width="480" alt="image" src="https://user-images.githubusercontent.com/64797182/183134780-b92c98bb-00f6-471d-884a-9610debd7d23.png">

**Comment by HerrHuang** [comment]
请问是在哪更改主题字体，我是 mac 系统，思源设置里更改编辑器字体没有反应。目前只根据介绍文档找到这个文件/Users/hjj/Documents/SiYuan/SiYuan/conf/appearance/themes/Dark+/style/module/custom-font-family.css，但是变成小白一脸懵逼不知道怎么改

**Comment by Zuoqiu-Yingyi** [comment]
> 请问是在哪更改主题字体，我是 mac 系统，思源设置里更改编辑器字体没有反应。目前只根据介绍文档找到这个文件/Users/hjj/Documents/SiYuan/SiYuan/conf/appearance/themes/Dark+/style/module/custom-font-family.css，但是变成小白一脸懵逼不知道怎么改

可以自定义该字符, 设置为字体有的即可, 步骤如下
1. 打开文件 `<工作空间>/data/widgets/custom.css`, 如果没有则新建
2. 在文件中写入如下内容并保存
    ```css
    :root {
        --custom-h-fold-mark: "XXX";
    }
    ```
3. 使用右上角的 <kbd>重新加载窗口</kbd> 按钮刷新页面
