### ISSUE TITLE
v1.2.6版本，在块的属性添加auto-num-f时，图片没有自动编号，请问有无问题排查建议QAQ

### ISSUE THREAD

**Issue by zwb709213019** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#97]
![图片](https://user-images.githubusercontent.com/20367302/187052967-4efb9dff-b03a-4003-b57e-4d2f68215e6e.png)
实际文档中都显示为图1
![图片](https://user-images.githubusercontent.com/20367302/187052983-c0ef7d17-3e73-403b-aa7f-f8d6fd044c91.png)

**Comment by Zuoqiu-Yingyi** [comment]
是个bug, 下个版本修复~

**Comment by zwb709213019** [comment]
> 是个bug, 下个版本修复~

好滴，谢谢回复~
