### ISSUE TITLE
替换页面，透明显示会降低效率

### ISSUE THREAD

**Issue by Geo123abc** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#98]
之前在搜索页面有这个问题，后来修好了，今天使用“替换”功能，发现在第二个输入框存在这样的问题

![](https://s3.bmp.ovh/imgs/2022/08/31/50cf257581389f8d.png)

**Comment by Zuoqiu-Yingyi** [comment]
是个 bug, 下个版本修复~
